import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { PERMISSION_CODE_DEFINITIONS, getPermissionCodeDefinition } from '@oes/common/authorization'
import { PERMISSION_CODE_SEED_ITEMS } from '../../src/scripts/permission-catalog'

/** Verifies the retired inverse generator cannot become a second Permission semantic source. */
describe('Common-owned permission catalog', () => {
  it('flows from Common definitions into Permission runtime seed items', () => {
    expect(PERMISSION_CODE_SEED_ITEMS.map((item) => item.code).sort()).toEqual(
      Object.keys(PERMISSION_CODE_DEFINITIONS).sort()
    )
    expect(getPermissionCodeDefinition('permission.list')).toBeDefined()
  })

  it('contains no generated banner or inverse package script', () => {
    const root = resolve(__dirname, '../../../../../common/src/authorization/permission-codes')
    expect(readFileSync(resolve(root, 'index.ts'), 'utf8')).not.toContain(
      'Generated by permission-service'
    )
    const packageJson = readFileSync(resolve(__dirname, '../../package.json'), 'utf8')
    expect(packageJson).not.toContain('permission-codes:generate-common')
  })
})
