import {
  AUTH_MANAGEMENT_PERMISSION_CODES,
  AUTH_SESSION_PERMISSION_CODES,
  HR_MANAGEMENT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_PERMISSION_CODES,
  PERMISSION_MANAGEMENT_PERMISSION_CODES,
  SALES_MANAGEMENT_PERMISSION_CODES,
  TENANT_ORG_MANAGEMENT_PERMISSION_CODES
} from '@oes/common/authorization'
import { BUILT_IN_ROLE_TEMPLATES } from '../../src/scripts/role-foundation'

describe('role foundation seed', () => {
  it('publishes the built-in tenant admin template baseline', () => {
    expect(BUILT_IN_ROLE_TEMPLATES).toContainEqual({
      code: 'tenant.admin',
      description: 'Built-in tenant administrator template for local and platform role bootstrap.',
      id: '2cf72f72-e04a-4946-b8c0-22f120f82001',
      name: '租户管理员',
      permissionCodes: [
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ROLE,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ROLE_DETAIL,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_ROLE,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_ROLE,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.DELETE_ROLE,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.SET_ACCOUNT_ROLES,
        PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_NAVIGATION_ENTRY,
        IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
        IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
        IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
        IDENTITY_ACCOUNT_PERMISSION_CODES.DELETE_ACCOUNT,
        AUTH_SESSION_PERMISSION_CODES.ADMIN_VIEW_USER_SESSIONS,
        AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
        AUTH_MANAGEMENT_PERMISSION_CODES.VIEW_AUDIT_EVENT,
        AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
        AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS,
        AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_TENANT_MFA_POLICY,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.LIST_ORG_TREE,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.VIEW_ORG_UNIT_DETAIL,
        HR_MANAGEMENT_PERMISSION_CODES.LIST_EMPLOYEE,
        HR_MANAGEMENT_PERMISSION_CODES.VIEW_EMPLOYEE_DETAIL,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.CREATE_ORG_UNIT,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.UPDATE_ORG_UNIT,
        TENANT_ORG_MANAGEMENT_PERMISSION_CODES.ARCHIVE_ORG_UNIT,
        SALES_MANAGEMENT_PERMISSION_CODES.LIST_QUOTE,
        SALES_MANAGEMENT_PERMISSION_CODES.GET_QUOTE,
        SALES_MANAGEMENT_PERMISSION_CODES.CREATE_QUOTE,
        SALES_MANAGEMENT_PERMISSION_CODES.UPDATE_QUOTE_DRAFT,
        SALES_MANAGEMENT_PERMISSION_CODES.PUBLISH_QUOTE,
        SALES_MANAGEMENT_PERMISSION_CODES.CONVERT_QUOTE_TO_ORDER,
        SALES_MANAGEMENT_PERMISSION_CODES.LIST_ORDER,
        SALES_MANAGEMENT_PERMISSION_CODES.VIEW_ORDER_DETAIL,
        SALES_MANAGEMENT_PERMISSION_CODES.SET_ORDER_COMMERCIAL_GATE,
        SALES_MANAGEMENT_PERMISSION_CODES.SUBMIT_FULFILLMENT_HANDOFF
      ]
    })
  })
})
