// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PERMISSION_ACCOUNT_SELF_PERMISSION_CODES = {
  GET_ROLES: 'permission.account.self.get_roles'
} as const
