// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export * from './account-self.permission-codes'
export * from './internal.permission-codes'
export * from './management.permission-codes'
export * from './role-instance.permission-codes'
export * from './role-template.permission-codes'
