// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PERMISSION_INTERNAL_PERMISSION_CODES = {
  PERMISSION_CHECK: 'permission.internal.permission.check',
  ACCOUNT_TERMINAL_ACCESS_RESOLVE: 'permission.internal.account_terminal_access.resolve',
  RESOURCE_CHECK: 'permission.internal.resource.check',
  QUERY_SCOPE_BUILD: 'permission.internal.query_scope.build',
  ACCOUNT_ACCESS_SUMMARY_RESOLVE: 'permission.internal.account_access_summary.resolve',
  ACCOUNT_NAVIGATION_RESOLVE: 'permission.internal.account_navigation.resolve',
  PRINCIPAL_AUTHORIZATION_RESOLVE: 'permission.internal.principal_authorization.resolve',
  DELEGATED_AUTHORIZATION_RESOLVE: 'permission.internal.delegated_authorization.resolve'
} as const
