// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PERMISSION_INTERNAL_PERMISSION_CODES = {
  PRINCIPAL_AUTHORIZATION_RESOLVE: 'permission.internal.principal_authorization.resolve',
  DELEGATED_AUTHORIZATION_RESOLVE: 'permission.internal.delegated_authorization.resolve'
} as const
