// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PERMISSION_MANAGEMENT_PERMISSION_CODES = {
  CREATE_PERMISSION: 'permission.create',
  UPDATE_PERMISSION: 'permission.update',
  DELETE_PERMISSION: 'permission.delete',
  VIEW_PERMISSION: 'permission.list',
  VIEW_PERMISSION_DETAIL: 'permission.get_by_id',
  VIEW_PERMISSION_DETAIL_BY_CODE: 'permission.get_by_code',
  VIEW_AUDIT_EVENT: 'permission.audit.list',
  VIEW_NAVIGATION_ENTRY: 'permission.navigation.entry.list',
  VIEW_NAVIGATION_ENTRY_DETAIL: 'permission.navigation.entry.get_by_key',
  CREATE_NAVIGATION_ENTRY: 'permission.navigation.entry.create',
  UPDATE_NAVIGATION_ENTRY: 'permission.navigation.entry.update',
  RESOLVE_NAVIGATION_PREVIEW: 'permission.navigation.resolve_preview',
  ASSIGN_ACCOUNT_ROLE: 'permission.account.assign_roles',
  REVOKE_ACCOUNT_ROLE: 'permission.account.assign_roles',
  VIEW_ACCOUNT_ROLE: 'permission.account.get_roles',
  SET_ACCOUNT_ROLES: 'permission.account.assign_roles',
  CREATE_POLICY: 'permission.policy.create',
  UPDATE_POLICY: 'permission.policy.update',
  DELETE_POLICY: 'permission.policy.delete',
  VIEW_POLICY: 'permission.policy.list'
} as const
