// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const ROLE_INSTANCE_PERMISSION_CODES = {
  CREATE: 'permission.role_instance.create',
  CREATE_FROM_TEMPLATE: 'permission.role_instance.create_from_template',
  UPDATE: 'permission.role_instance.update',
  DELETE: 'permission.role_instance.delete',
  ASSIGN_PERMISSIONS: 'permission.role_instance.assign_permissions',
  SYNC_FROM_TEMPLATE: 'permission.role_instance.sync_from_template',
  LIST: 'permission.role_instance.list',
  GET_BY_ID: 'permission.role_instance.get_by_id'
} as const
