// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const ROLE_TEMPLATE_PERMISSION_CODES = {
  CREATE: 'permission.role_template.create',
  UPDATE: 'permission.role_template.update',
  DELETE: 'permission.role_template.delete',
  ASSIGN_PERMISSIONS: 'permission.role_template.assign_permissions',
  LIST: 'permission.role_template.list',
  GET_BY_ID: 'permission.role_template.get_by_id'
} as const
