const assert = require('node:assert/strict')
const { readFileSync } = require('node:fs')
const { join } = require('node:path')
const test = require('node:test')
const protobuf = require('protobufjs')

const contractRoot = __dirname

// This test freezes the three Auth-only Permission decision RPCs and their trusted snapshot fields.
test('permission decision proto exposes the frozen issuance and delegated contracts', () => {
  const root = protobuf.loadSync(join(contractRoot, 'permission_check.proto'))
  const service = root.lookupService('permission_service.PermissionCheckService')

  assert.deepEqual(
    Object.keys(service.methods)
      .filter((name) => name.startsWith('Resolve'))
      .sort(),
    [
      'ResolveDelegatedAuthorization',
      'ResolveExternalMachineAuthorizationSnapshot',
      'ResolvePrincipalAuthorization',
      'ResolveWorkloadIssuance'
    ]
  )

  assertMessageFields(root, 'ResolvePrincipalAuthorizationRequest', [
    'principalType',
    'principalId',
    'scopeLevel',
    'tenantId',
    'orgId',
    'targetAudience',
    'requestedBusinessPermissionCodes',
    'sessionReference',
    'securityReference',
    'delegatedUpperBound'
  ])
  assertMessageFields(root, 'ResolveWorkloadIssuanceRequest', [
    'originalWorkloadSpiffeId',
    'targetAudience',
    'requestedInternalPermissionCodes',
    'scopeLevel',
    'tenantId',
    'orgId',
    'principalType',
    'principalId',
    'issuancePolicyVersion'
  ])
  assertMessageFields(root, 'ResolveDelegatedAuthorizationRequest', [
    'humanPrincipalId',
    'scopeLevel',
    'tenantId',
    'orgId',
    'targetAudience',
    'operationKey',
    'requestedPermissionCodes',
    'delegatedUpperBound',
    'ownerAuthorization'
  ])
  assertMessageFields(root, 'DelegatedAuthorizationUpperBound', [
    'humanPrincipalId',
    'sessionReference',
    'securityReference',
    'delegationReference',
    'delegationVersion',
    'delegationActive',
    'delegationPermissionCodes',
    'agentPrincipalReference',
    'agentPrincipalVersion',
    'agentPrincipalActive',
    'agentPermissionCodes',
    'toolContractReference',
    'toolContractVersion',
    'toolContractActive',
    'toolPermissionCodes'
  ])
  assertMessageFields(root, 'OwnerAuthorizationSnapshot', [
    'actionReference',
    'policyReference',
    'policyVersion',
    'current',
    'permissionCodes',
    'codeRiskBaseline',
    'effectiveRiskClass',
    'resourcePolicyAllowed',
    'resourcePolicyReference'
  ])
})

// This test keeps the two Permission-owned INTERNAL codes in the leased Common namespace.
test('permission INTERNAL code source contains only the principal and delegated resolver codes', () => {
  const source = readFileSync(
    join(
      contractRoot,
      '../../authorization/permission-codes/permission/internal.permission-codes.ts'
    ),
    'utf8'
  )

  assert.match(
    source,
    /PRINCIPAL_AUTHORIZATION_RESOLVE:\s*'permission\.internal\.principal_authorization\.resolve'/
  )
  assert.match(
    source,
    /DELEGATED_AUTHORIZATION_RESOLVE:\s*'permission\.internal\.delegated_authorization\.resolve'/
  )
  assert.doesNotMatch(source, /collaboration\.internal\./)
})

// This helper compares the exact camelCase field surface generated by protobufjs.
function assertMessageFields(root, messageName, expectedFields) {
  const message = root.lookupType(`permission_service.${messageName}`)
  assert.deepEqual(Object.keys(message.fields), expectedFields)
}
