// File: contracts/permission_service/permission_check.proto
syntax = "proto3";

package permission_service;

option java_multiple_files = true;
option java_package = "com.oes.permission.v1";

// 权限检查服务
service PermissionCheckService {
  // 检查用户是否拥有指定权限
  rpc CheckPermission(CheckPermissionRequest) returns (CheckPermissionResponse);
  // 检查用户权限范围
  rpc CheckPermissionScope(CheckPermissionRequest) returns (CheckPermissionResponse);
}

// 权限检查请求
message CheckPermissionRequest {
  // 账户ID
  string account_id = 1;
  // 权限代码
  string permission_code = 2;
}

// 权限检查响应
message CheckPermissionResponse {
  // 是否通过
  bool pass = 1;
  // 权限范围列表
  repeated PermissionScope scopes = 2;
}

// 权限范围
message PermissionScope {
  // 范围类型
  PermissionScopeType type = 1;
  // 范围值
  string value = 2;
}

// 权限范围类型
enum PermissionScopeType {
  // 未指定
  PERMISSION_SCOPE_TYPE_UNSPECIFIED = 0;
  // 租户级别
  PERMISSION_SCOPE_TYPE_TENANT = 1;
  // 组织级别
  PERMISSION_SCOPE_TYPE_ORG = 2;
  // 资源级别
  PERMISSION_SCOPE_TYPE_RESOURCE = 3;
  // 自身级别
  PERMISSION_SCOPE_TYPE_SELF = 4;
}
