/** DEPRECATED_PERMISSION_CODES remains a non-active cleanup list and is never part of the runtime catalog. */
export const DEPRECATED_PERMISSION_CODES = [
  'auth.login_method.self.list',
  'auth.login_method.self.manage',
  'auth.session.self.list',
  'auth.session.self.revoke',
  'crm.activity.create',
  'crm.contact.manage',
  'crm.duplicate.viewRestricted',
  'crm.opportunity.manage',
  'crm.source.manage',
  'extension.designer.product.collect',
  'extension.designer.project.create',
  'extension.designer.submit_to_oes',
  'identity.account.self.update_profile',
  'identity.contact.asset.update',
  'identity.org.membership.add',
  'identity.org.membership.remove',
  'identity.org.membership.set_primary',
  'item_master.item.set_composition',
  'permission.account.self.get_roles',
  'permission.policy.delete',
  'permission.role.create',
  'permission.role.delete_by_id',
  'permission.role.get_by_id',
  'permission.role.list',
  'permission.role.update',
  'permission.role_instance.delete_by_id',
  'permission.role_instance.permission.assign',
  'permission.role_instance.permission.revoke',
  'permission.role_template.delete_by_id',
  'permission.role_template.permission.assign',
  'permission.role_template.permission.revoke'
] as const
