/** TenantOnboardingRunStatus enumerates the durable lifecycle of one tenant onboarding Saga run. */
export enum TenantOnboardingRunStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  FAILED_RETRYABLE = 'FAILED_RETRYABLE',
  FAILED_NEEDS_MANUAL_REVIEW = 'FAILED_NEEDS_MANUAL_REVIEW',
  SUCCEEDED = 'SUCCEEDED'
}

/** TenantOnboardingStepStatus enumerates durable per-step execution states. */
export enum TenantOnboardingStepStatus {
  NOT_STARTED = 'NOT_STARTED',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED'
}

/** TenantOnboardingStepKey names every owner-service handoff in tenant onboarding. */
export enum TenantOnboardingStepKey {
  REGISTER_ORGANIZATION_PARTY = 'REGISTER_ORGANIZATION_PARTY',
  CREATE_TENANT_WITH_ROOT_ORG = 'CREATE_TENANT_WITH_ROOT_ORG',
  BIND_ORGANIZATION_TENANT_PARTY = 'BIND_ORGANIZATION_TENANT_PARTY',
  CREATE_FIRST_ADMIN_ACCOUNT = 'CREATE_FIRST_ADMIN_ACCOUNT',
  BOOTSTRAP_FIRST_ADMIN_LOGIN_METHODS = 'BOOTSTRAP_FIRST_ADMIN_LOGIN_METHODS',
  REQUIRE_FIRST_LOGIN_PASSWORD_SETUP = 'REQUIRE_FIRST_LOGIN_PASSWORD_SETUP',
  ENSURE_TENANT_ADMIN_ROLE = 'ENSURE_TENANT_ADMIN_ROLE',
  GRANT_TENANT_ADMIN_ROLE = 'GRANT_TENANT_ADMIN_ROLE'
}
