/** TOKENS centralizes the DI tokens used across the crm-service runtime graph. */
export const TOKENS = {
  CRM_ACCOUNT_REPOSITORY: Symbol('CRM_ACCOUNT_REPOSITORY'),
  CRM_AUDIT_WRITER: Symbol('CRM_AUDIT_WRITER'),
  CRM_TRANSACTION_RUNNER: Symbol('CRM_TRANSACTION_RUNNER'),
  TENANT_PARTY_LOOKUP_PORT: Symbol('TENANT_PARTY_LOOKUP_PORT'),
  TENANT_PARTY_RESOLUTION_PORT: Symbol('TENANT_PARTY_RESOLUTION_PORT')
} as const
