// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const SALES_MANAGEMENT_PERMISSION_CODES = {
  LIST_QUOTE: 'sales.quote.list',
  GET_QUOTE: 'sales.quote.get_by_id',
  CREATE_QUOTE: 'sales.quote.create',
  UPDATE_QUOTE_DRAFT: 'sales.quote.update_draft',
  PUBLISH_QUOTE: 'sales.quote.publish',
  CONVERT_QUOTE_TO_ORDER: 'sales.quote.convert_to_order',
  LIST_ORDER: 'sales.order.list',
  VIEW_ORDER_DETAIL: 'sales.order.get_by_id',
  SET_ORDER_COMMERCIAL_GATE: 'sales.order.set_commercial_gate',
  SUBMIT_FULFILLMENT_HANDOFF: 'sales.order.submit_fulfillment_handoff'
} as const
