// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const SALES_PRICING_PERMISSION_CODES = {
  READ_PRICE_LIST: 'sales.pricing.price_list.read',
  MANAGE_PRICE_LIST: 'sales.pricing.price_list.manage',
  READ_CUSTOMER_AGREEMENT: 'sales.pricing.customer_agreement.read',
  MANAGE_CUSTOMER_AGREEMENT: 'sales.pricing.customer_agreement.manage',
  PREVIEW_QUOTE_LINE: 'sales.pricing.preview_quote_line'
} as const
