// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const NOTIFICATION_INTERNAL_PERMISSION_CODES = {
  AUTH_DISPATCH: 'notification.internal.auth.dispatch'
} as const
