// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const AUTH_SESSION_PERMISSION_CODES = {
  ADMIN_VIEW_USER_SESSIONS: 'auth.session.admin.view',
  ADMIN_REVOKE_SESSION: 'auth.session.admin.revoke'
} as const
