// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const HR_MANAGEMENT_PERMISSION_CODES = {
  LIST_EMPLOYEE: 'hr.employee.list',
  VIEW_EMPLOYEE_DETAIL: 'hr.employee.get_by_id',
  CREATE_EMPLOYEE: 'hr.employee.create',
  CREATE_EMPLOYMENT: 'hr.employment.create',
  END_EMPLOYMENT: 'hr.employment.end',
  CHANGE_PRIMARY_EMPLOYMENT: 'hr.employment.change_primary'
} as const
