packages:
  - 'app/browser-extension'
  - 'src/services/*'
  - 'src/services/auxiliary/*'
  - 'src/services/business/*'
  - 'src/services/system/*'
  - 'src/site-runtime/*'
  - 'src/site-runtime/external-site-template/runtime'
  - 'src/site-runtime/external-site-template/storefront'
  - 'src/common'
