packages:
  - 'app/browser-extension'
  - 'src/services/*'
  - 'src/services/auxiliary/*'
  - 'src/services/business/*'
  - 'src/services/system/*'
  - 'src/site-runtime/*'
  - 'src/site-runtime/external-site-template/runtime'
  - 'src/site-runtime/external-site-template/storefront'
  - 'src/site-runtime/meilong-ceramics-site/runtime'
  - 'src/site-runtime/meilong-ceramics-site/storefront'
  - 'src/common'
strictDepBuilds: true
allowBuilds:
  '@nestjs/core': false
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  bcrypt: true
  esbuild: true
  grpc-tools: true
  prisma: true
  protobufjs: false
