// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const ITEM_MASTER_INTERNAL_PERMISSION_CODES = {
  RESOLVE_MANUFACTURABLE_ITEM: 'item_master.internal.manufacturable_item.resolve',
  RESOLVE_STOCKABLE_ITEM: 'item_master.internal.stockable_item.resolve',
  RESOLVE_PURCHASABLE_ITEM: 'item_master.internal.purchasable_item.resolve'
} as const
