import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import {
  AUTH_MANAGEMENT_PERMISSION_CODES,
  AUTH_SELF_PERMISSION_CODES,
  AUTH_SESSION_PERMISSION_CODES,
  BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES,
  COLLABORATION_ANNOTATION_PERMISSION_CODES,
  COLLABORATION_TASK_PERMISSION_CODES,
  CRM_MANAGEMENT_PERMISSION_CODES,
  FINANCE_MANAGEMENT_PERMISSION_CODES,
  HR_MANAGEMENT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_PERMISSION_CODES,
  IDENTITY_ACCOUNT_SELF_PERMISSION_CODES,
  IDENTITY_INTERNAL_PERMISSION_CODES,
  IDENTITY_MACHINE_PERMISSION_CODES,
  IDENTITY_TENANT_PERMISSION_CODES,
  ITEM_MASTER_MANAGEMENT_PERMISSION_CODES,
  MES_MANAGEMENT_PERMISSION_CODES,
  PERMISSION_ACCOUNT_SELF_PERMISSION_CODES,
  PERMISSION_INTERNAL_PERMISSION_CODES,
  PERMISSION_MANAGEMENT_PERMISSION_CODES,
  PROCUREMENT_MANAGEMENT_PERMISSION_CODES,
  PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES,
  PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES,
  ROLE_INSTANCE_PERMISSION_CODES,
  ROLE_TEMPLATE_PERMISSION_CODES,
  SALES_MANAGEMENT_PERMISSION_CODES,
  SALES_PRICING_PERMISSION_CODES,
  SITE_MANAGEMENT_PERMISSION_CODES,
  SRM_MANAGEMENT_PERMISSION_CODES,
  TENANT_ORG_MANAGEMENT_PERMISSION_CODES,
  TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES,
  WMS_MANAGEMENT_PERMISSION_CODES
} from './permission-catalog'

type PermissionCodeRecord = Record<string, string>

type CommonPermissionCodeFileDefinition =
  | {
      exports: string[]
      kind: 'index'
      relativePath: string
    }
  | {
      constName: string
      kind: 'const'
      records: PermissionCodeRecord
      relativePath: string
    }

const COMMON_PERMISSION_CODES_ROOT = resolve(
  __dirname,
  '../../../../../../src/common/src/authorization/permission-codes'
)
const GENERATED_FILE_BANNER =
  '// Generated by permission-service permission-codes:generate-common. Do not edit manually.'

const COMMON_PERMISSION_CODE_FILES: CommonPermissionCodeFileDefinition[] = [
  {
    kind: 'index',
    relativePath: 'index.ts',
    exports: [
      './auth',
      './browser-activity',
      './collaboration',
      './crm',
      './finance',
      './hr',
      './identity',
      './item-master',
      './mes',
      './procurement',
      './permission',
      './public-entry',
      './sales',
      './site-management',
      './srm',
      './tenant-org',
      './terminal-device',
      './wms'
    ]
  },
  {
    kind: 'index',
    relativePath: 'browser-activity/index.ts',
    exports: ['./audit.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'browser-activity/audit.permission-codes.ts',
    constName: 'BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES',
    records: BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'auth/index.ts',
    exports: [
      './auth-management.permission-codes',
      './self.permission-codes',
      './session.permission-codes'
    ]
  },
  {
    kind: 'const',
    relativePath: 'auth/auth-management.permission-codes.ts',
    constName: 'AUTH_MANAGEMENT_PERMISSION_CODES',
    records: AUTH_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'auth/self.permission-codes.ts',
    constName: 'AUTH_SELF_PERMISSION_CODES',
    records: AUTH_SELF_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'auth/session.permission-codes.ts',
    constName: 'AUTH_SESSION_PERMISSION_CODES',
    records: AUTH_SESSION_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'collaboration/index.ts',
    exports: ['./annotation.permission-codes', './task.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'collaboration/annotation.permission-codes.ts',
    constName: 'COLLABORATION_ANNOTATION_PERMISSION_CODES',
    records: COLLABORATION_ANNOTATION_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'collaboration/task.permission-codes.ts',
    constName: 'COLLABORATION_TASK_PERMISSION_CODES',
    records: COLLABORATION_TASK_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'crm/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'crm/management.permission-codes.ts',
    constName: 'CRM_MANAGEMENT_PERMISSION_CODES',
    records: CRM_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'finance/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'finance/management.permission-codes.ts',
    constName: 'FINANCE_MANAGEMENT_PERMISSION_CODES',
    records: FINANCE_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'hr/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'hr/management.permission-codes.ts',
    constName: 'HR_MANAGEMENT_PERMISSION_CODES',
    records: HR_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'identity/index.ts',
    exports: [
      './account.permission-codes',
      './account-self.permission-codes',
      './internal.permission-codes',
      './machine.permission-codes',
      './tenant.permission-codes'
    ]
  },
  {
    kind: 'const',
    relativePath: 'identity/internal.permission-codes.ts',
    constName: 'IDENTITY_INTERNAL_PERMISSION_CODES',
    records: IDENTITY_INTERNAL_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'identity/account.permission-codes.ts',
    constName: 'IDENTITY_ACCOUNT_PERMISSION_CODES',
    records: IDENTITY_ACCOUNT_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'identity/account-self.permission-codes.ts',
    constName: 'IDENTITY_ACCOUNT_SELF_PERMISSION_CODES',
    records: IDENTITY_ACCOUNT_SELF_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'identity/machine.permission-codes.ts',
    constName: 'IDENTITY_MACHINE_PERMISSION_CODES',
    records: IDENTITY_MACHINE_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'identity/tenant.permission-codes.ts',
    constName: 'IDENTITY_TENANT_PERMISSION_CODES',
    records: IDENTITY_TENANT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'item-master/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'item-master/management.permission-codes.ts',
    constName: 'ITEM_MASTER_MANAGEMENT_PERMISSION_CODES',
    records: ITEM_MASTER_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'mes/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'mes/management.permission-codes.ts',
    constName: 'MES_MANAGEMENT_PERMISSION_CODES',
    records: MES_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'permission/index.ts',
    exports: [
      './account-self.permission-codes',
      './internal.permission-codes',
      './management.permission-codes',
      './role-instance.permission-codes',
      './role-template.permission-codes'
    ]
  },
  {
    kind: 'const',
    relativePath: 'permission/internal.permission-codes.ts',
    constName: 'PERMISSION_INTERNAL_PERMISSION_CODES',
    records: PERMISSION_INTERNAL_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'permission/account-self.permission-codes.ts',
    constName: 'PERMISSION_ACCOUNT_SELF_PERMISSION_CODES',
    records: PERMISSION_ACCOUNT_SELF_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'permission/management.permission-codes.ts',
    constName: 'PERMISSION_MANAGEMENT_PERMISSION_CODES',
    records: PERMISSION_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'permission/role-instance.permission-codes.ts',
    constName: 'ROLE_INSTANCE_PERMISSION_CODES',
    records: ROLE_INSTANCE_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'permission/role-template.permission-codes.ts',
    constName: 'ROLE_TEMPLATE_PERMISSION_CODES',
    records: ROLE_TEMPLATE_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'procurement/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'procurement/management.permission-codes.ts',
    constName: 'PROCUREMENT_MANAGEMENT_PERMISSION_CODES',
    records: PROCUREMENT_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'public-entry/index.ts',
    exports: ['./short-link.permission-codes', './business-card.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'public-entry/short-link.permission-codes.ts',
    constName: 'PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES',
    records: PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'public-entry/business-card.permission-codes.ts',
    constName: 'PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES',
    records: PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'sales/index.ts',
    exports: ['./management.permission-codes', './pricing.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'sales/management.permission-codes.ts',
    constName: 'SALES_MANAGEMENT_PERMISSION_CODES',
    records: SALES_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'const',
    relativePath: 'sales/pricing.permission-codes.ts',
    constName: 'SALES_PRICING_PERMISSION_CODES',
    records: SALES_PRICING_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'site-management/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'site-management/management.permission-codes.ts',
    constName: 'SITE_MANAGEMENT_PERMISSION_CODES',
    records: SITE_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'srm/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'srm/management.permission-codes.ts',
    constName: 'SRM_MANAGEMENT_PERMISSION_CODES',
    records: SRM_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'tenant-org/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'tenant-org/management.permission-codes.ts',
    constName: 'TENANT_ORG_MANAGEMENT_PERMISSION_CODES',
    records: TENANT_ORG_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'terminal-device/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'terminal-device/management.permission-codes.ts',
    constName: 'TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES',
    records: TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES
  },
  {
    kind: 'index',
    relativePath: 'wms/index.ts',
    exports: ['./management.permission-codes']
  },
  {
    kind: 'const',
    relativePath: 'wms/management.permission-codes.ts',
    constName: 'WMS_MANAGEMENT_PERMISSION_CODES',
    records: WMS_MANAGEMENT_PERMISSION_CODES
  }
]

/** renderIndexFile preserves the current re-export layout for one common permission-code index file. */
function renderIndexFile(exports: string[]): string {
  return [
    GENERATED_FILE_BANNER,
    ...exports.map((specifier) => `export * from '${specifier}'`)
  ].join('\n')
}

/** renderPermissionCodeConstFile preserves the current object-literal export shape for one permission-code group file. */
function renderPermissionCodeConstFile(constName: string, records: PermissionCodeRecord): string {
  const entries = Object.entries(records)
  if (entries.length === 0) {
    return [GENERATED_FILE_BANNER, `export const ${constName} = {} as const`].join('\n')
  }

  const lines = entries.map(([key, value], index) => {
    const suffix = index === entries.length - 1 ? '' : ','
    return `  ${key}: '${value}'${suffix}`
  })
  return [GENERATED_FILE_BANNER, `export const ${constName} = {`, ...lines, `} as const`].join('\n')
}

/** renderCommonPermissionCodeFiles returns the full common permission-code tree as relative paths plus file content. */
export function renderCommonPermissionCodeFiles(): Map<string, string> {
  const renderedEntries = COMMON_PERMISSION_CODE_FILES.map(
    (definition) =>
      [
        definition.relativePath,
        definition.kind === 'index'
          ? renderIndexFile(definition.exports)
          : renderPermissionCodeConstFile(definition.constName, definition.records)
      ] as const
  )

  return new Map(renderedEntries)
}

/** syncCommonPermissionCodeFiles writes the generated common permission-code files to disk under the shared common package. */
export function syncCommonPermissionCodeFiles(
  targetRootDir = COMMON_PERMISSION_CODES_ROOT
): string[] {
  const renderedFiles = renderCommonPermissionCodeFiles()
  const writtenPaths: string[] = []

  for (const [relativePath, content] of renderedFiles) {
    const absolutePath = resolve(targetRootDir, relativePath)
    mkdirSync(dirname(absolutePath), { recursive: true })
    writeFileSync(absolutePath, `${content}\n`, 'utf8')
    writtenPaths.push(absolutePath)
  }

  return writtenPaths
}

/** main executes the common permission-code sync as a one-shot CLI for local maintenance workflows. */
function main(): void {
  const writtenPaths = syncCommonPermissionCodeFiles()
  process.stdout.write(
    `Synced ${writtenPaths.length} permission-code files into ${COMMON_PERMISSION_CODES_ROOT}\n`
  )
}

if (require.main === module) {
  main()
}
