import {
  AUTH_MANAGEMENT_PERMISSION_CODES,
  AUTH_SESSION_PERMISSION_CODES,
  IDENTITY_ACCOUNT_PERMISSION_CODES,
  PERMISSION_MANAGEMENT_PERMISSION_CODES
} from '@oes/common/authorization'

export interface BuiltInRoleTemplateSeed {
  code: string
  description: string
  id: string
  name: string
  permissionCodes: string[]
}

// Publishes the built-in role templates that local and platform environments should always be able to bootstrap.
export const BUILT_IN_ROLE_TEMPLATES: BuiltInRoleTemplateSeed[] = [
  {
    id: '2cf72f72-e04a-4946-b8c0-22f120f82001',
    code: 'tenant.admin',
    name: '租户管理员',
    description: 'Built-in tenant administrator template for local and platform role bootstrap.',
    permissionCodes: [
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_PERMISSION,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ROLE_DETAIL,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.CREATE_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.UPDATE_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.DELETE_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.VIEW_ACCOUNT_ROLE,
      PERMISSION_MANAGEMENT_PERMISSION_CODES.SET_ACCOUNT_ROLES,
      IDENTITY_ACCOUNT_PERMISSION_CODES.LIST_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.CREATE_ACCOUNT,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_PROFILE,
      IDENTITY_ACCOUNT_PERMISSION_CODES.UPDATE_ACCOUNT_STATUS,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_VIEW_USER_SESSIONS,
      AUTH_SESSION_PERMISSION_CODES.ADMIN_REVOKE_SESSION,
      AUTH_MANAGEMENT_PERMISSION_CODES.VIEW_AUDIT_EVENT,
      AUTH_MANAGEMENT_PERMISSION_CODES.BOOTSTRAP_ACCOUNT_CREDENTIALS,
      AUTH_MANAGEMENT_PERMISSION_CODES.MANAGE_ACCOUNT_LOGIN_METHODS
    ]
  }
]
