// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PARTY_INTERNAL_PERMISSION_CODES = {
  REGISTER_TENANT_PARTY: 'party.internal.register_tenant_party',
  DEACTIVATE_TENANT_PARTY: 'party.internal.deactivate_tenant_party',
  GET_TENANT_PARTY_BY_ID: 'party.internal.get_tenant_party_by_id',
  RESOLVE_TENANT_PARTY_BY_IDENTIFIER: 'party.internal.resolve_tenant_party_by_identifier',
  RESOLVE_TENANT_PARTY_FOR_CONSUMER: 'party.internal.resolve_tenant_party_for_consumer',
  SEARCH_TENANT_PARTY_CANDIDATES: 'party.internal.search_tenant_party_candidates'
} as const
