export enum MfaType {
  TOTP = 'TOTP',
  EMAIL_OTP = 'EMAIL_OTP',
  SMS_OTP = 'SMS_OTP',
  BACKUP_CODE = 'BACKUP_CODE',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
  HARDWARE_TOKEN = 'HARDWARE_TOKEN',
  BIOMETRIC = 'BIOMETRIC'
}
