import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger'
import { Type } from 'class-transformer'
import {
  IsDateString,
  IsEnum,
  IsInt,
  IsOptional,
  IsString,
  Max,
  MaxLength,
  Min,
  MinLength
} from 'class-validator'

export enum MfaBindingTypeDto {
  EMAIL_OTP = 'EMAIL_OTP',
  SMS_OTP = 'SMS_OTP',
  TOTP = 'TOTP',
  BACKUP_CODE = 'BACKUP_CODE'
}

// Defines the payload used to enable or disable one self-service MFA binding type.
export class MfaBindingMutationDto {
  @ApiProperty({
    enum: MfaBindingTypeDto,
    enumName: 'MfaBindingType',
    description: 'MFA binding type targeted by the self-service mutation.'
  })
  @IsEnum(MfaBindingTypeDto)
  type: MfaBindingTypeDto
}

// Defines the payload used to activate a previously initialized TOTP binding.
export class ActivateTotpBindingDto {
  @ApiProperty({
    description: 'Binding identifier returned by the TOTP initialization step.',
    maxLength: 128,
    example: 'mfa_01HZY2Q8S9K3'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(128)
  bindingId: string

  @ApiProperty({
    description: 'Verification code generated by the authenticator application.',
    maxLength: 64,
    example: '123456'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  code: string
}

// Defines the payload used by an authenticated user to change their own password.
export class ChangeOwnPasswordDto {
  @ApiProperty({
    description: 'Current password used to verify the self-service password change.',
    minLength: 1
  })
  @IsString()
  @MinLength(1)
  currentPassword: string

  @ApiProperty({
    description: 'New password to apply to the user login methods.',
    minLength: 8
  })
  @IsString()
  @MinLength(8)
  newPassword: string
}

// Defines the payload used to request one authenticated self-service email binding challenge.
export class RequestEmailContactBindingChallengeDto {
  @ApiProperty({
    description: 'Email address that should receive the contact-binding verification code.'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(320)
  email: string
}

// Defines the payload used to verify one authenticated self-service email binding challenge.
export class VerifyEmailContactBindingDto extends RequestEmailContactBindingChallengeDto {
  @ApiProperty({
    description: 'One-time verification code delivered to the requested email address.'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  otp: string
}

// Defines the payload used to request one authenticated self-service phone binding challenge.
export class RequestPhoneContactBindingChallengeDto {
  @ApiProperty({
    description: 'Canonical phone number that should receive the contact-binding verification code.'
  })
  @IsString()
  @MinLength(6)
  @MaxLength(32)
  phone: string
}

// Defines the payload used to verify one authenticated self-service phone binding challenge.
export class VerifyPhoneContactBindingDto extends RequestPhoneContactBindingChallengeDto {
  @ApiProperty({
    description: 'One-time verification code delivered to the requested phone number.'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  otp: string
}

export enum LoginHistoryResultDto {
  FAILED = 'FAILED',
  SUCCESS = 'SUCCESS'
}

// Defines the allowed query filters for the authenticated user's self-service login history.
export class SelfLoginHistoryQueryDto {
  @ApiPropertyOptional({
    enum: LoginHistoryResultDto,
    enumName: 'LoginHistoryResult',
    description: 'Filters login history by success or failure outcome.'
  })
  @IsOptional()
  @IsEnum(LoginHistoryResultDto)
  result?: LoginHistoryResultDto

  @ApiPropertyOptional({
    description: 'Optional ISO-8601 lower bound for the login attempt occurrence time.'
  })
  @IsOptional()
  @IsDateString()
  occurredAtFrom?: string

  @ApiPropertyOptional({
    description: 'Optional ISO-8601 upper bound for the login attempt occurrence time.'
  })
  @IsOptional()
  @IsDateString()
  occurredAtTo?: string

  @ApiPropertyOptional({
    description: 'Opaque cursor returned by the previous login-history page.'
  })
  @IsOptional()
  @IsString()
  cursor?: string

  @ApiPropertyOptional({
    description: 'Maximum number of login-history records returned in one page.',
    minimum: 1,
    maximum: 100
  })
  @IsOptional()
  @Type(() => Number)
  @IsInt()
  @Min(1)
  @Max(100)
  pageSize?: number
}
