import { ApiProperty } from '@nestjs/swagger'
import { IsEnum, IsString, MaxLength, MinLength } from 'class-validator'

export enum MfaBindingTypeDto {
  EMAIL_OTP = 'EMAIL_OTP',
  SMS_OTP = 'SMS_OTP',
  TOTP = 'TOTP',
  BACKUP_CODE = 'BACKUP_CODE'
}

// Defines the payload used to enable or disable one self-service MFA binding type.
export class MfaBindingMutationDto {
  @ApiProperty({
    enum: MfaBindingTypeDto,
    enumName: 'MfaBindingType',
    description: 'MFA binding type targeted by the self-service mutation.'
  })
  @IsEnum(MfaBindingTypeDto)
  type: MfaBindingTypeDto
}

// Defines the payload used to activate a previously initialized TOTP binding.
export class ActivateTotpBindingDto {
  @ApiProperty({
    description: 'Binding identifier returned by the TOTP initialization step.',
    maxLength: 128,
    example: 'mfa_01HZY2Q8S9K3'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(128)
  bindingId: string

  @ApiProperty({
    description: 'Verification code generated by the authenticator application.',
    maxLength: 64,
    example: '123456'
  })
  @IsString()
  @MinLength(1)
  @MaxLength(64)
  code: string
}
