export const OTP_USAGES = {
    LOGIN: "LOGIN",
    REGISTER: "REGISTER",
    RESET_PASSWORD: "RESET_PASSWORD",
    MFA_VERIFY: "MFA_VERIFY"
}

export const OTP_TYPES = {
    EMAIL: "EMAIL",
    PHONE: "PHONE",
    TOTP: "TOTP",
    BACKUP_CODE: "BACKUP_CODE"
}

export const LOGIN_METHOD_TYPES = {
    EMAIL: "EMAIL",
    PHONE: "PHONE",
    OAUTH_OPENID: "OAUTH_OPENID"
}

export const CREDENTIAL_TYPES = {
    PASSWORD: "PASSWORD",
    EMAIL_OTP: "EMAIL_OTP",
    PHONE_OTP: "PHONE_OTP",
    OAUTH: "OAUTH"
}