// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const SRM_INTERNAL_PERMISSION_CODES = {
  RESOLVE_ACTIVE_SUPPLIER: 'srm.internal.supplier_profile.resolve_active',
  RESOLVE_ACTIVE_SUPPLIER_OFFERING: 'srm.internal.supplier_offering.resolve_active'
} as const
