// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const SRM_MANAGEMENT_PERMISSION_CODES = {
  LIST_SUPPLIER_PROFILE: 'srm.supplier_profile.list',
  VIEW_SUPPLIER_DETAIL: 'srm.supplier_profile.get_by_id',
  CREATE_SUPPLIER_PROFILE: 'srm.supplier_profile.create',
  UPDATE_SUPPLIER_PROFILE_BASICS: 'srm.supplier_profile.update_basics',
  BIND_SUPPLIER_TO_TENANT_PARTY: 'srm.supplier_profile.bind_tenant_party',
  CHANGE_SUPPLIER_STATUS: 'srm.supplier_profile.change_status',
  UPSERT_SUPPLIER_CONTACT: 'srm.supplier_contact.upsert',
  UPSERT_SUPPLIER_ADDRESS: 'srm.supplier_address.upsert',
  LIST_SUPPLIER_OFFERINGS_BY_SUPPLIER: 'srm.supplier_offering.list_by_supplier',
  LIST_SUPPLIER_OFFERINGS_BY_ITEM: 'srm.supplier_offering.list_by_item',
  UPSERT_SUPPLIER_OFFERING: 'srm.supplier_offering.upsert'
} as const
