import { Test } from '@nestjs/testing'
import { of } from 'rxjs'
import { SrmTrustedExecutionModule } from '../../src/modules/srm-trusted-execution.module'
import { SrmPartyTrustedGrpcClient } from '../../src/infrastructure/adapters/party-trusted-grpc.client'
import { SrmPartyMachineSourceCredentialClient } from '../../src/infrastructure/adapters/srm-party-machine-source-credential.client'
import { SrmPartyMachineSourceCredentialProvider } from '../../src/infrastructure/adapters/srm-party-machine-source-credential.provider'
import { SrmPartyExecutionTokenExchangeClient } from '../../src/infrastructure/adapters/srm-party-execution-token-exchange.client'
import { SrmPartyTrustedGrpcExecutionProducer } from '../../src/infrastructure/adapters/srm-party-trusted-grpc-execution.producer'

const code='party.internal.get_tenant_party_by_id'; const audience='urn:oes:service:party-service'; const trace='00-0123456789abcdef0123456789abcdef-0123456789abcdef-01'
describe('SRM Party trusted execution', () => {
  const env=process.env
  beforeEach(()=>{process.env={...env,AUTH_EXECUTION_ISSUER:'https://issuer.example',OES_WORKLOAD_SPIFFE_ID:'spiffe://oes/srm-service',SRM_PARTY_MACHINE_PRINCIPAL_ID:'machine-srm',SRM_PARTY_MACHINE_WORKLOAD_BINDING_ID:'binding-srm',SRM_PARTY_MACHINE_WORKLOAD_BINDING_VERSION:'1'}})
  afterAll(()=>{process.env=env})
  it('resolves its dedicated client, source provider, exchange, and producer through TestingModule',async()=>{const m=await Test.createTestingModule({imports:[SrmTrustedExecutionModule]}).compile();for(const t of [SrmPartyTrustedGrpcClient,SrmPartyMachineSourceCredentialClient,SrmPartyMachineSourceCredentialProvider,SrmPartyExecutionTokenExchangeClient,SrmPartyTrustedGrpcExecutionProducer])expect(m.get(t)).toBeDefined();await m.close()})
  it('sends its own principal and binding selector and accepts only Bearer source credentials',async()=>{const c=new SrmPartyMachineSourceCredentialClient();const call=jest.fn(()=>of({tokenType:'Bearer',sourceCredential:'source'}));(c as any).getService=()=>({issueMachineWorkloadSourceCredential:call});await expect(c.issue()).resolves.toBe('source');expect(call).toHaveBeenCalledWith({machinePrincipalId:'machine-srm',machineWorkloadBindingId:'binding-srm',machineWorkloadBindingVersion:'1'},expect.anything());(c as any).getService=()=>({issueMachineWorkloadSourceCredential:()=>of({tokenType:'Bearer',sourceCredential:''})});await expect(c.issue()).rejects.toThrow('PARTY_CALLER_SOURCE_CREDENTIAL_INVALID')})
  it('fails closed for missing config or rejected source without entering the provider callback',async()=>{const c=new SrmPartyMachineSourceCredentialClient();delete process.env.SRM_PARTY_MACHINE_WORKLOAD_BINDING_ID;await expect(c.issue()).rejects.toThrow('PARTY_CALLER_FOUNDATION_UNAVAILABLE');process.env.SRM_PARTY_MACHINE_WORKLOAD_BINDING_ID='binding-srm';(c as any).getService=()=>({issueMachineWorkloadSourceCredential:()=>{throw new Error('source credential rejected')}});const p=new SrmPartyMachineSourceCredentialProvider(c);const downstream=jest.fn(async()=>undefined);await expect(p.run(downstream)).rejects.toThrow('source credential rejected');expect(downstream).not.toHaveBeenCalled()})
  it('executes its exchange client and producer typed mapping for STS and ET failures',async()=>{const e=new SrmPartyExecutionTokenExchangeClient();const sts=jest.fn(()=>of({accessToken:'',tokenType:'Bearer',grantedAudience:audience,grantedPermissionCodes:[code]}));(e as any).getService=()=>({exchangeExecutionToken:sts});await expect(e.exchange({targetAudience:audience,requestedPermissionCodes:[code]},{} as never)).resolves.toMatchObject({accessToken:'',grantedAudience:audience});expect(sts).toHaveBeenCalledWith({targetAudience:audience,requestedPermissionCodes:[code]},expect.anything());const source={accessor:{},run:async()=>{throw new Error('STS rejected promise')}};const producer=new SrmPartyTrustedGrpcExecutionProducer(source as never,e);await expect(producer.createMetadata(code,'request-1',trace)).rejects.toThrow('PARTY_CALLER_FOUNDATION_UNAVAILABLE')})
})
