// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PROCUREMENT_INTERNAL_PERMISSION_CODES = {
  RESOLVE_RECEIVING_EXPECTATION_FOR_RECEIPT: 'procurement.internal.receiving_expectation.resolve_for_receipt'
} as const
