import crypto from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { spawnSync } from 'node:child_process'
import { pathToFileURL } from 'node:url'
import {
  EXPECTED_BACKEND_PACKAGE_COUNT,
  EXPECTED_PRISMA_SERVICE_COUNT,
  defaultRepositoryRoot,
  discoverBackendPackages,
  repositoryRelative
} from './reproducible-build-lib.mjs'

const GENERATED_MARKER = '# Generated by pnpm env:bootstrap; local development only.'
const REQUIRED_TEMPLATE_KEYS = Object.freeze([
  'OES_ENVIRONMENT',
  'OES_TASK_KEY',
  'OES_POSTGRES_HOST',
  'OES_POSTGRES_PORT',
  'OES_POSTGRES_USER',
  'OES_POSTGRES_PASSWORD',
  'OES_DATABASE_PREFIX'
])
const PLACEHOLDER_PATTERN =
  /(?:<[^>]+>|\$\{[^}]+\}|\{\{[^}]+\}\}|change[\s_-]*me|replace[\s_-]*me|your[\s_-]*(?:password|secret|token)|placeholder|\btodo\b|\btbd\b|\brequired\b)/i
const TASK_KEY_PATTERN = /^[a-z0-9][a-z0-9_]{2,39}$/

/** Parses the scalar subset used by the versioned local environment template. */
export function parseEnvironmentFile(contents, source = '.env') {
  const values = new Map()
  const lines = contents.split(/\r?\n/)

  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index].trim()
    if (!line || line.startsWith('#')) continue
    const match = /^([A-Z][A-Z0-9_]*)=(.*)$/.exec(line)
    if (!match) throw new Error(`ENV_INVALID_LINE source=${source} line=${index + 1}`)
    if (values.has(match[1])) throw new Error(`ENV_DUPLICATE_KEY source=${source} key=${match[1]}`)
    let value = match[2].trim()
    const startsWithQuote = value.startsWith('"') || value.startsWith("'")
    const endsWithQuote = value.endsWith('"') || value.endsWith("'")
    if (startsWithQuote !== endsWithQuote || (startsWithQuote && value[0] !== value.at(-1))) {
      throw new Error(`ENV_UNTERMINATED_QUOTE source=${source} line=${index + 1}`)
    }
    if (value.length >= 2 && startsWithQuote) {
      value = value.slice(1, -1)
    }
    values.set(match[1], value)
  }
  return values
}

/** Normalizes an explicit or derived identifier for task-owned local resources. */
export function normalizeTaskKey(value) {
  const normalized = value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  if (normalized === 'auto') throw new Error('ENV_TASK_KEY_RESERVED value=auto')
  if (!TASK_KEY_PATTERN.test(normalized)) throw new Error(`ENV_TASK_KEY_INVALID value=${value}`)
  return normalized
}

/** Derives one stable worktree-specific key without recording host paths in versioned files. */
export function deriveTaskKey(repositoryRoot) {
  const parentName = (path.basename(path.dirname(repositoryRoot)) || 'worktree')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 31)
  const digest = crypto
    .createHash('sha256')
    .update(path.resolve(repositoryRoot))
    .digest('hex')
    .slice(0, 8)
  return normalizeTaskKey(`${parentName}_${digest}`)
}

/** Reads and validates the sanitized source template before any local file is created. */
export function readEnvironmentTemplate(repositoryRoot) {
  const templatePath = path.join(repositoryRoot, '.env.example')
  if (!fs.existsSync(templatePath)) throw new Error('ENV_TEMPLATE_MISSING path=.env.example')
  const values = parseEnvironmentFile(fs.readFileSync(templatePath, 'utf8'), '.env.example')
  for (const key of REQUIRED_TEMPLATE_KEYS) {
    const value = values.get(key)
    if (!value) throw new Error(`ENV_TEMPLATE_KEY_MISSING key=${key}`)
    if (key !== 'OES_TASK_KEY' && PLACEHOLDER_PATTERN.test(value)) {
      throw new Error(`ENV_TEMPLATE_PLACEHOLDER key=${key}`)
    }
  }
  const unknownKeys = [...values.keys()].filter((key) => !REQUIRED_TEMPLATE_KEYS.includes(key))
  if (unknownKeys.length) throw new Error(`ENV_TEMPLATE_KEY_UNKNOWN keys=${unknownKeys.join(',')}`)
  if (values.get('OES_ENVIRONMENT') !== 'development') {
    throw new Error('ENV_TEMPLATE_UNSAFE_ENVIRONMENT expected=development')
  }
  if (values.get('OES_TASK_KEY') !== 'auto') {
    normalizeTaskKey(values.get('OES_TASK_KEY'))
  }
  validatePostgresInputs(values, '.env.example')
  return values
}

/** Validates local-only PostgreSQL inputs without probing or mutating a database. */
function validatePostgresInputs(values, source) {
  const host = values.get('OES_POSTGRES_HOST')
  if (!['127.0.0.1', 'localhost'].includes(host)) {
    throw new Error(`ENV_POSTGRES_HOST_NOT_LOCAL source=${source} host=${host}`)
  }
  const port = Number(values.get('OES_POSTGRES_PORT'))
  if (!Number.isInteger(port) || port < 1 || port > 65535) {
    throw new Error(`ENV_POSTGRES_PORT_INVALID source=${source}`)
  }
  for (const key of ['OES_POSTGRES_USER', 'OES_POSTGRES_PASSWORD', 'OES_DATABASE_PREFIX']) {
    const value = values.get(key)
    if (!value || PLACEHOLDER_PATTERN.test(value))
      throw new Error(`ENV_VALUE_INVALID source=${source} key=${key}`)
  }
}

/** Produces a PostgreSQL-safe database identifier bounded to 63 characters. */
function databaseName(prefix, taskKey, serviceName) {
  const base = `${prefix}_${taskKey}_${serviceName}`
    .toLowerCase()
    .replace(/-service$/g, '')
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
  if (base.length <= 63) return base
  const digest = crypto.createHash('sha256').update(base).digest('hex').slice(0, 8)
  return `${base.slice(0, 54)}_${digest}`
}

/** Serializes the generated root environment in stable key order. */
function renderRootEnvironment(template, taskKey) {
  const values = new Map(template)
  values.set('OES_TASK_KEY', taskKey)
  return `${GENERATED_MARKER}\n${REQUIRED_TEMPLATE_KEYS.map((key) => `${key}=${values.get(key)}`).join('\n')}\n`
}

/** Serializes the minimal backend environment needed by Prisma and local runtime defaults. */
function renderServiceEnvironment(template, taskKey, service) {
  const lines = [
    GENERATED_MARKER,
    `OES_TASK_KEY=${taskKey}`,
    'NODE_ENV=development',
    `MODULE_NAME=${service.name}`
  ]
  if (!service.prismaSchema) return `${lines.join('\n')}\n`

  const database = databaseName(template.get('OES_DATABASE_PREFIX'), taskKey, service.name)
  const url = new URL('postgresql://127.0.0.1')
  url.username = template.get('OES_POSTGRES_USER')
  url.password = template.get('OES_POSTGRES_PASSWORD')
  url.hostname = template.get('OES_POSTGRES_HOST')
  url.port = template.get('OES_POSTGRES_PORT')
  url.pathname = `/${database}`
  url.searchParams.set('schema', 'public')
  lines.push(`DATABASE_URL="${url.toString()}"`)
  return `${lines.join('\n')}\n`
}

/** Atomically creates or refreshes only files already owned by this generator. */
function writeGeneratedFile(filePath, contents, { force, temporaryRoot }) {
  if (fs.existsSync(filePath)) {
    const current = fs.readFileSync(filePath, 'utf8')
    if (current === contents) return 'unchanged'
    if (!force)
      throw new Error(`ENV_FILE_EXISTS path=${filePath} hint=rerun-with---force-after-review`)
    if (!current.startsWith(GENERATED_MARKER)) {
      throw new Error(`ENV_FILE_NOT_GENERATOR_OWNED path=${filePath}`)
    }
  }
  const targetDigest = crypto.createHash('sha256').update(filePath).digest('hex').slice(0, 16)
  const temporary = path.join(temporaryRoot, `${process.pid}-${targetDigest}`)
  fs.writeFileSync(temporary, contents, { encoding: 'utf8', flag: 'wx', mode: 0o600 })
  fs.renameSync(temporary, filePath)
  fs.chmodSync(filePath, 0o600)
  return 'written'
}

/** Preflights every destination so a later ownership conflict cannot leave a partial environment. */
function assertGeneratedFileWritable(filePath, contents, { force }) {
  try {
    if (fs.lstatSync(filePath).isSymbolicLink())
      throw new Error(`ENV_FILE_SYMLINK path=${filePath}`)
  } catch (error) {
    if (!(error instanceof Error) || error.code !== 'ENOENT') throw error
  }
  if (!fs.existsSync(filePath)) return
  const current = fs.readFileSync(filePath, 'utf8')
  if (current === contents) return
  if (!force)
    throw new Error(`ENV_FILE_EXISTS path=${filePath} hint=rerun-with---force-after-review`)
  if (!current.startsWith(GENERATED_MARKER)) {
    throw new Error(`ENV_FILE_NOT_GENERATOR_OWNED path=${filePath}`)
  }
}

/** Confirms generated and crash-residue paths are ignored while versioned inputs remain visible. */
function assertGitIgnoreContract(repositoryRoot, targets) {
  if (!fs.existsSync(path.join(repositoryRoot, '.git'))) return
  const ignoredPaths = [
    ...targets.map((target) => repositoryRelative(repositoryRoot, target.path)),
    '.tmp/oes-env-bootstrap/probe'
  ]
  for (const ignoredPath of ignoredPaths) {
    const result = spawnSync('git', ['check-ignore', '--quiet', '--no-index', '--', ignoredPath], {
      cwd: repositoryRoot
    })
    if (result.error) throw result.error
    if (result.status !== 0) throw new Error(`ENV_PATH_NOT_IGNORED path=${ignoredPath}`)
  }
  const templateResult = spawnSync(
    'git',
    ['check-ignore', '--quiet', '--no-index', '--', '.env.example'],
    { cwd: repositoryRoot }
  )
  if (templateResult.error) throw templateResult.error
  if (templateResult.status === 0) throw new Error('ENV_TEMPLATE_IGNORED path=.env.example')
  if (templateResult.status !== 1) {
    throw new Error(`ENV_GITIGNORE_CHECK_FAILED exit=${templateResult.status}`)
  }
}

/** Creates task-owned ignored environment files from the sanitized repository template. */
export function bootstrapEnvironment({
  repositoryRoot = defaultRepositoryRoot(),
  expectedBackendCount = EXPECTED_BACKEND_PACKAGE_COUNT,
  expectedPrismaCount = EXPECTED_PRISMA_SERVICE_COUNT,
  taskKey,
  force = false,
  output = process.stdout
} = {}) {
  const template = readEnvironmentTemplate(repositoryRoot)
  const requestedTaskKey =
    taskKey === undefined
      ? template.get('OES_TASK_KEY') === 'auto'
        ? deriveTaskKey(repositoryRoot)
        : template.get('OES_TASK_KEY')
      : taskKey
  const resolvedTaskKey = normalizeTaskKey(requestedTaskKey)
  const backendPackages = discoverBackendPackages(repositoryRoot)
  const services = backendPackages.filter((entry) => entry.prismaSchema)
  if (backendPackages.length !== expectedBackendCount) {
    throw new Error(
      `ENV_BACKEND_COUNT_MISMATCH expected=${expectedBackendCount} actual=${backendPackages.length}`
    )
  }
  if (services.length !== expectedPrismaCount) {
    throw new Error(
      `ENV_SERVICE_COUNT_MISMATCH expected=${expectedPrismaCount} actual=${services.length}`
    )
  }

  const rootEnvironmentPath = path.join(repositoryRoot, '.env')
  const targets = [
    {
      path: rootEnvironmentPath,
      contents: renderRootEnvironment(template, resolvedTaskKey)
    }
  ]
  for (const service of backendPackages) {
    const serviceEnvironmentPath = path.join(service.directory, '.env')
    targets.push({
      path: serviceEnvironmentPath,
      contents: renderServiceEnvironment(template, resolvedTaskKey, service)
    })
  }
  for (const target of targets) assertGeneratedFileWritable(target.path, target.contents, { force })
  assertGitIgnoreContract(repositoryRoot, targets)
  const temporaryParent = path.join(repositoryRoot, '.tmp')
  const temporaryParentExisted = fs.existsSync(temporaryParent)
  if (fs.existsSync(temporaryParent) && fs.lstatSync(temporaryParent).isSymbolicLink()) {
    throw new Error('ENV_TEMP_ROOT_SYMLINK')
  }
  const temporaryRoot = path.join(temporaryParent, 'oes-env-bootstrap')
  if (fs.existsSync(temporaryRoot) && fs.lstatSync(temporaryRoot).isSymbolicLink()) {
    throw new Error('ENV_TEMP_ROOT_SYMLINK')
  }
  fs.mkdirSync(temporaryRoot, { recursive: true, mode: 0o700 })
  const results = targets.map((target) => ({
    path: target.path,
    status: writeGeneratedFile(target.path, target.contents, { force, temporaryRoot })
  }))
  try {
    fs.rmdirSync(temporaryRoot)
    if (!temporaryParentExisted) fs.rmdirSync(temporaryParent)
  } catch (error) {
    if (!(error instanceof Error) || !['ENOTEMPTY', 'ENOENT'].includes(error.code)) throw error
  }

  output.write(`ENV_TASK_KEY=${resolvedTaskKey}\n`)
  output.write(`ENV_BACKEND_COUNT=${backendPackages.length}\n`)
  output.write(`ENV_SERVICE_COUNT=${services.length}\n`)
  for (const result of results) {
    output.write(
      `ENV_FILE status=${result.status} path=${repositoryRelative(repositoryRoot, result.path)}\n`
    )
  }
  output.write(`ENV_BOOTSTRAP=PASS files=${results.length}\n`)
  return { backendPackages, results, services, taskKey: resolvedTaskKey }
}

/** Checks that generated local files remain isolated, complete, and internally consistent. */
export function checkEnvironment({
  repositoryRoot = defaultRepositoryRoot(),
  expectedBackendCount = EXPECTED_BACKEND_PACKAGE_COUNT,
  expectedPrismaCount = EXPECTED_PRISMA_SERVICE_COUNT,
  output = process.stdout
} = {}) {
  readEnvironmentTemplate(repositoryRoot)
  const rootEnvironmentPath = path.join(repositoryRoot, '.env')
  if (!fs.existsSync(rootEnvironmentPath))
    throw new Error('ENV_ROOT_MISSING hint=run-pnpm-env:bootstrap')
  const rootContents = fs.readFileSync(rootEnvironmentPath, 'utf8')
  if (!rootContents.startsWith(GENERATED_MARKER)) throw new Error('ENV_ROOT_NOT_GENERATOR_OWNED')
  const rootValues = parseEnvironmentFile(rootContents, '.env')
  for (const key of REQUIRED_TEMPLATE_KEYS) {
    const value = rootValues.get(key)
    if (!value || PLACEHOLDER_PATTERN.test(value) || value === 'auto') {
      throw new Error(`ENV_ROOT_VALUE_INVALID key=${key}`)
    }
  }
  if (rootValues.get('OES_ENVIRONMENT') !== 'development') {
    throw new Error('ENV_ROOT_UNSAFE_ENVIRONMENT expected=development')
  }
  const taskKey = normalizeTaskKey(rootValues.get('OES_TASK_KEY'))
  validatePostgresInputs(rootValues, '.env')
  if (rootContents !== renderRootEnvironment(rootValues, taskKey)) {
    throw new Error('ENV_ROOT_CONTENT_MISMATCH')
  }

  const backendPackages = discoverBackendPackages(repositoryRoot)
  const services = backendPackages.filter((entry) => entry.prismaSchema)
  if (backendPackages.length !== expectedBackendCount) {
    throw new Error(
      `ENV_BACKEND_COUNT_MISMATCH expected=${expectedBackendCount} actual=${backendPackages.length}`
    )
  }
  if (services.length !== expectedPrismaCount) {
    throw new Error(
      `ENV_SERVICE_COUNT_MISMATCH expected=${expectedPrismaCount} actual=${services.length}`
    )
  }
  const environmentTargets = [
    { path: rootEnvironmentPath },
    ...backendPackages.map((service) => ({ path: path.join(service.directory, '.env') }))
  ]
  assertGitIgnoreContract(repositoryRoot, environmentTargets)
  const databases = new Set()
  for (const service of backendPackages) {
    const relativeEnvironmentPath = repositoryRelative(
      repositoryRoot,
      path.join(service.directory, '.env')
    )
    const environmentPath = path.join(service.directory, '.env')
    if (!fs.existsSync(environmentPath))
      throw new Error(`ENV_SERVICE_MISSING path=${relativeEnvironmentPath}`)
    const contents = fs.readFileSync(environmentPath, 'utf8')
    if (!contents.startsWith(GENERATED_MARKER)) {
      throw new Error(`ENV_SERVICE_NOT_GENERATOR_OWNED path=${relativeEnvironmentPath}`)
    }
    const values = parseEnvironmentFile(contents, relativeEnvironmentPath)
    if (values.get('OES_TASK_KEY') !== taskKey) {
      throw new Error(`ENV_SERVICE_TASK_KEY_MISMATCH service=${service.name}`)
    }
    if (values.get('NODE_ENV') !== 'development') {
      throw new Error(`ENV_SERVICE_UNSAFE_ENVIRONMENT service=${service.name}`)
    }
    if (values.get('MODULE_NAME') !== service.name) {
      throw new Error(`ENV_SERVICE_MODULE_MISMATCH service=${service.name}`)
    }
    const expectedContents = renderServiceEnvironment(rootValues, taskKey, service)
    if (!service.prismaSchema) {
      if (values.has('DATABASE_URL')) {
        throw new Error(`ENV_GATEWAY_DATABASE_URL_FORBIDDEN service=${service.name}`)
      }
      if (contents !== expectedContents) {
        throw new Error(`ENV_SERVICE_CONTENT_MISMATCH service=${service.name}`)
      }
      continue
    }
    const databaseUrl = values.get('DATABASE_URL')
    if (!databaseUrl || PLACEHOLDER_PATTERN.test(databaseUrl)) {
      throw new Error(`ENV_SERVICE_DATABASE_URL_INVALID service=${service.name}`)
    }
    let parsed
    try {
      parsed = new URL(databaseUrl)
    } catch {
      throw new Error(`ENV_SERVICE_DATABASE_URL_MALFORMED service=${service.name}`)
    }
    if (!['postgres:', 'postgresql:'].includes(parsed.protocol)) {
      throw new Error(`ENV_SERVICE_DATABASE_PROTOCOL_INVALID service=${service.name}`)
    }
    if (parsed.hostname !== rootValues.get('OES_POSTGRES_HOST')) {
      throw new Error(`ENV_SERVICE_DATABASE_HOST_MISMATCH service=${service.name}`)
    }
    const databasePort = parsed.port || '5432'
    if (databasePort !== rootValues.get('OES_POSTGRES_PORT')) {
      throw new Error(`ENV_SERVICE_DATABASE_PORT_MISMATCH service=${service.name}`)
    }
    if (decodeURIComponent(parsed.username) !== rootValues.get('OES_POSTGRES_USER')) {
      throw new Error(`ENV_SERVICE_DATABASE_USER_MISMATCH service=${service.name}`)
    }
    if (decodeURIComponent(parsed.password) !== rootValues.get('OES_POSTGRES_PASSWORD')) {
      throw new Error(`ENV_SERVICE_DATABASE_PASSWORD_MISMATCH service=${service.name}`)
    }
    const expectedDatabase = databaseName(
      rootValues.get('OES_DATABASE_PREFIX'),
      taskKey,
      service.name
    )
    const actualDatabase = decodeURIComponent(parsed.pathname.slice(1))
    if (actualDatabase !== expectedDatabase || parsed.searchParams.get('schema') !== 'public') {
      throw new Error(`ENV_SERVICE_DATABASE_NOT_TASK_OWNED service=${service.name}`)
    }
    if (databases.has(actualDatabase))
      throw new Error(`ENV_SERVICE_DATABASE_DUPLICATE database=${actualDatabase}`)
    databases.add(actualDatabase)
    if (contents !== expectedContents) {
      throw new Error(`ENV_SERVICE_CONTENT_MISMATCH service=${service.name}`)
    }
  }

  output.write(`ENV_TASK_KEY=${taskKey}\n`)
  output.write(`ENV_BACKEND_COUNT=${backendPackages.length}\n`)
  output.write(`ENV_SERVICE_COUNT=${services.length}\n`)
  output.write(`ENV_DATABASE_COUNT=${databases.size}\n`)
  output.write('ENV_CHECK=PASS\n')
  return { backendPackages, databases, services, taskKey }
}

/** Parses the bounded CLI accepted by the versioned environment commands. */
function parseArguments(argv) {
  const [command, ...options] = argv
  const parsed = { command, force: false, taskKey: undefined }
  for (const option of options) {
    if (option === '--') continue
    if (option === '--force') parsed.force = true
    else if (option.startsWith('--task-key=')) parsed.taskKey = option.slice('--task-key='.length)
    else throw new Error(`ENV_ARGUMENT_UNKNOWN value=${option}`)
  }
  return parsed
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : undefined
if (invokedPath === import.meta.url) {
  try {
    const arguments_ = parseArguments(process.argv.slice(2))
    if (arguments_.command === 'bootstrap') {
      bootstrapEnvironment({ force: arguments_.force, taskKey: arguments_.taskKey })
    } else if (arguments_.command === 'check') {
      if (arguments_.force || arguments_.taskKey) throw new Error('ENV_CHECK_ARGUMENT_INVALID')
      checkEnvironment()
    } else {
      throw new Error('ENV_COMMAND_REQUIRED expected=bootstrap|check')
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  }
}
