export const REPO = {
  USER: Symbol('IDENTITY_REPO_USER'),
  ACCOUNT: Symbol('IDENTITY_REPO_ACCOUNT'),
  ACCOUNT_CONTACT_ASSET: Symbol('IDENTITY_REPO_ACCOUNT_CONTACT_ASSET'),
  EMPLOYEE_BINDING: Symbol('IDENTITY_REPO_EMPLOYEE_BINDING'),
  SERVICE_ACCOUNT: Symbol('IDENTITY_REPO_SERVICE_ACCOUNT'),
  API_KEY: Symbol('IDENTITY_REPO_API_KEY'),
  AUDIT_EVENT: Symbol('IDENTITY_REPO_AUDIT_EVENT')
}
