export const REPO = {
  USER: Symbol('IDENTITY_REPO_USER'),
  ACCOUNT: Symbol('IDENTITY_REPO_ACCOUNT'),
  TENANT: Symbol('IDENTITY_REPO_TENANT'),
  ORG: Symbol('IDENTITY_REPO_ORG'),
  ACCOUNT_ORG_MEMBERSHIP: Symbol('IDENTITY_REPO_ACCOUNT_ORG_MEMBERSHIP')
}
