// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const IDENTITY_ACCOUNT_PERMISSION_CODES = {
  LIST_ACCOUNT: 'identity.account.list',
  CREATE_ACCOUNT: 'identity.account.create',
  UPDATE_ACCOUNT_STATUS: 'identity.account.update_status',
  UPDATE_ACCOUNT_PROFILE: 'identity.account.profile.update',
  DELETE_ACCOUNT: 'identity.account.delete',
  ASSIGN_CONTACT_ASSET: 'identity.contact.asset.assign',
  UPDATE_CONTACT_ASSET: 'identity.contact.asset.update',
  SET_CONTACT_ASSET_STATUS: 'identity.contact.asset.set_status',
  SET_PRIMARY_CONTACT_ASSET: 'identity.contact.asset.set_primary',
  RELEASE_CONTACT_ASSET: 'identity.contact.asset.release',
  ASSIGN_WORK_EMAIL: 'identity.contact.work_email.assign',
  REVOKE_WORK_EMAIL: 'identity.contact.work_email.revoke',
  SET_PRIMARY_WORK_EMAIL: 'identity.contact.work_email.set_primary',
  SET_WORK_EMAIL_STATUS: 'identity.contact.work_email.set_status',
  ASSIGN_WORK_PHONE: 'identity.contact.work_phone.assign',
  REVOKE_WORK_PHONE: 'identity.contact.work_phone.revoke',
  SET_PRIMARY_WORK_PHONE: 'identity.contact.work_phone.set_primary',
  SET_WORK_PHONE_STATUS: 'identity.contact.work_phone.set_status'
} as const
