// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export * from './account.permission-codes'
export * from './account-self.permission-codes'
export * from './machine.permission-codes'
export * from './tenant.permission-codes'
