// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const IDENTITY_INTERNAL_PERMISSION_CODES = {
  MACHINE_PRINCIPAL_RESOLVE: 'identity.internal.machine_principal.resolve'
} as const
