import { Test } from '@nestjs/testing'
import { of } from 'rxjs'
import { HrTrustedExecutionModule } from '../../src/modules/hr-trusted-execution.module'
import { HrPartyTrustedGrpcClient } from '../../src/infrastructure/adapters/party-trusted-grpc.client'
import { HrPartyMachineSourceCredentialClient } from '../../src/infrastructure/adapters/hr-party-machine-source-credential.client'
import { HrPartyMachineSourceCredentialProvider } from '../../src/infrastructure/adapters/hr-party-machine-source-credential.provider'
import { HrPartyExecutionTokenExchangeClient } from '../../src/infrastructure/adapters/hr-party-execution-token-exchange.client'
import { HrPartyTrustedGrpcExecutionProducer } from '../../src/infrastructure/adapters/hr-party-trusted-grpc-execution.producer'
const code='party.internal.register_tenant_party'; const audience='urn:oes:service:party-service'; const trace='00-0123456789abcdef0123456789abcdef-0123456789abcdef-01'
describe('HR Party trusted execution',()=>{const env=process.env
  beforeEach(()=>{process.env={...env,AUTH_EXECUTION_ISSUER:'https://issuer.example',OES_WORKLOAD_SPIFFE_ID:'spiffe://oes/hr-service',HR_PARTY_MACHINE_PRINCIPAL_ID:'machine-hr',HR_PARTY_MACHINE_WORKLOAD_BINDING_ID:'binding-hr',HR_PARTY_MACHINE_WORKLOAD_BINDING_VERSION:'1'}});afterAll(()=>{process.env=env})
  it('resolves its dedicated DI graph',async()=>{const m=await Test.createTestingModule({imports:[HrTrustedExecutionModule]}).compile();for(const t of [HrPartyTrustedGrpcClient,HrPartyMachineSourceCredentialClient,HrPartyMachineSourceCredentialProvider,HrPartyExecutionTokenExchangeClient,HrPartyTrustedGrpcExecutionProducer])expect(m.get(t)).toBeDefined();await m.close()})
  it('uses HR selector and rejects empty source credential',async()=>{const c=new HrPartyMachineSourceCredentialClient();const rpc=jest.fn(()=>of({tokenType:'Bearer',sourceCredential:'source'}));(c as any).get=()=>({issueMachineWorkloadSourceCredential:rpc});await expect(c.issue()).resolves.toBe('source');expect(rpc).toHaveBeenCalledWith({machinePrincipalId:'machine-hr',machineWorkloadBindingId:'binding-hr',machineWorkloadBindingVersion:'1'},expect.anything());(c as any).get=()=>({issueMachineWorkloadSourceCredential:()=>of({tokenType:'Bearer',sourceCredential:''})});await expect(c.issue()).rejects.toThrow('PARTY_CALLER_SOURCE_CREDENTIAL_INVALID')})
  it('fails closed before callback for missing config and source rejection',async()=>{const c=new HrPartyMachineSourceCredentialClient();delete process.env.HR_PARTY_MACHINE_WORKLOAD_BINDING_VERSION;await expect(c.issue()).rejects.toThrow('PARTY_CALLER_FOUNDATION_UNAVAILABLE');process.env.HR_PARTY_MACHINE_WORKLOAD_BINDING_VERSION='1';(c as any).get=()=>({issueMachineWorkloadSourceCredential:()=>{throw new Error('source credential rejected')}});const p=new HrPartyMachineSourceCredentialProvider(c);const cb=jest.fn(async()=>undefined);await expect(p.run(cb)).rejects.toThrow('source credential rejected');expect(cb).not.toHaveBeenCalled()})
  it('executes HR exchange and maps STS rejection through producer',async()=>{const e=new HrPartyExecutionTokenExchangeClient();(e as any).get=()=>({exchangeExecutionToken:()=>of({accessToken:'',tokenType:'Bearer',grantedAudience:audience,grantedPermissionCodes:[code]})});await expect(e.exchange({targetAudience:audience,requestedPermissionCodes:[code]},{} as never)).resolves.toMatchObject({grantedAudience:audience});const producer=new HrPartyTrustedGrpcExecutionProducer({accessor:{},run:async()=>{throw new Error('STS rejected promise')}} as never,e);await expect(producer.createMetadata(code,'request-1',trace)).rejects.toThrow('PARTY_CALLER_FOUNDATION_UNAVAILABLE')})
})
