export const INTERNAL_SERVICE_AUTHENTICATOR = Symbol('INTERNAL_SERVICE_AUTHENTICATOR')
export const GRPC_METADATA_PROPAGATION_FACTORY = Symbol('GRPC_METADATA_PROPAGATION_FACTORY')
export const GATEWAY_PERMISSION_TRUSTED_METADATA_PROVIDER = Symbol(
  'GATEWAY_PERMISSION_TRUSTED_METADATA_PROVIDER'
)
export const OPERATOR_CONTEXT_SIGNER = Symbol('OPERATOR_CONTEXT_SIGNER')
export const OPERATOR_CONTEXT_VERIFIER = Symbol('OPERATOR_CONTEXT_VERIFIER')
export const OPERATOR_PERMISSION_RESOLVER = Symbol('OPERATOR_PERMISSION_RESOLVER')
