export const AUTHORIZATION_METADATA_KEY = 'authorization'
export const INTERNAL_SERVICE_NAME_METADATA_KEY = 'x-internal-service-name'
export const OPERATOR_CONTEXT_METADATA_KEY = 'x-operator-context'
export const REQUEST_ID_METADATA_KEY = 'x-request-id'
export const TRACE_ID_METADATA_KEY = 'x-trace-id'
export const TRACEPARENT_METADATA_KEY = 'traceparent'
export const TRACESTATE_METADATA_KEY = 'tracestate'
