export const REPO = {
  TERMINAL_DEVICE: Symbol('TERMINAL_DEVICE_REPO_TERMINAL_DEVICE'),
  ENROLLMENT: Symbol('TERMINAL_DEVICE_REPO_ENROLLMENT'),
  RUNTIME_SNAPSHOT: Symbol('TERMINAL_DEVICE_REPO_RUNTIME_SNAPSHOT'),
  VERSION_POLICY: Symbol('TERMINAL_DEVICE_REPO_VERSION_POLICY'),
  AUDIT_EVENT: Symbol('TERMINAL_DEVICE_REPO_AUDIT_EVENT')
}
