// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const MES_MANAGEMENT_PERMISSION_CODES = {
  READ_MANUFACTURING_SPEC: 'mes.manufacturing_spec.read',
  MANAGE_MANUFACTURING_SPEC: 'mes.manufacturing_spec.manage',
  READ_MOLD_DESIGN: 'mes.mold_design.read',
  MANAGE_MOLD_DESIGN: 'mes.mold_design.manage',
  READ_PRODUCTION_MOLD_INSTANCE: 'mes.production_mold_instance.read',
  MANAGE_PRODUCTION_MOLD_INSTANCE: 'mes.production_mold_instance.manage',
  READ_WORK_CENTER_MOLD_STATUS: 'mes.work_center_mold_status.read',
  RECORD_MOLD_USAGE: 'mes.mold_usage.record',
  MANAGE_MOLD_LIFE: 'mes.mold_life.manage'
} as const
