// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const MES_MANAGEMENT_PERMISSION_CODES = {
  READ_PRODUCTION_SPEC: 'mes.production_spec.read',
  MANAGE_PRODUCTION_SPEC: 'mes.production_spec.manage',
  READ_MOLD_DESIGN: 'mes.mold_design.read',
  MANAGE_MOLD_DESIGN: 'mes.mold_design.manage',
  READ_PRODUCTION_MOLD: 'mes.production_mold.read',
  MANAGE_PRODUCTION_MOLD: 'mes.production_mold.manage',
  READ_TOOLING_INSTALLATION: 'mes.tooling_installation.read',
  MANAGE_TOOLING_INSTALLATION: 'mes.tooling_installation.manage',
  RECORD_MOLD_USAGE: 'mes.mold_usage.record',
  MANAGE_MOLD_LIFE: 'mes.mold_life.manage'
} as const
