// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const BROWSER_ACTIVITY_AUDIT_PERMISSION_CODES = {
  POLICY_READ: 'browser_activity.policy.read',
  POLICY_MANAGE: 'browser_activity.policy.manage',
  OVERVIEW_READ: 'browser_activity.overview.read',
  EMPLOYEE_DETAIL_READ: 'browser_activity.employee_detail.read',
  URL_DETAIL_READ: 'browser_activity.url_detail.read'
} as const
