export const CONTACT_ASSET_TYPES = {
  WORK_EMAIL: 'WORK_EMAIL',
  WORK_PHONE: 'WORK_PHONE',
  WECHAT: 'WECHAT',
  WHATSAPP: 'WHATSAPP',
  EXTERNAL_COMMUNICATION_ACCOUNT: 'EXTERNAL_COMMUNICATION_ACCOUNT',
  OTHER_SOCIAL: 'OTHER_SOCIAL'
} as const

export const CONTACT_ASSET_STATUSES = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED',
  PENDING_HANDOVER: 'PENDING_HANDOVER',
  RELEASED: 'RELEASED',
  REVOKED: 'REVOKED'
} as const

export const CONTACT_ASSET_PATTERNS = {
  WORK_EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  WORK_PHONE: /^\+?[0-9][0-9\- ]{5,19}$/,
  WHATSAPP: /^\+?[0-9][0-9\- ]{5,19}$/
} as const
