export const MACHINE_PRINCIPAL_SCOPE_LEVELS = {
  SYSTEM: 'SYSTEM',
  TENANT: 'TENANT'
} as const

export const MACHINE_PRINCIPAL_SCOPE_LEVEL_VALUES = Object.values(MACHINE_PRINCIPAL_SCOPE_LEVELS)

export const MACHINE_PRINCIPAL_TYPES = {
  INTERNAL_SERVICE: 'INTERNAL_SERVICE',
  EXTERNAL_INTEGRATION: 'EXTERNAL_INTEGRATION',
  AI_AGENT: 'AI_AGENT',
  AUTOMATION_BOT: 'AUTOMATION_BOT'
} as const

export const MACHINE_PRINCIPAL_TYPE_VALUES = Object.values(MACHINE_PRINCIPAL_TYPES)

export const MACHINE_PRINCIPAL_STATUSES = {
  ACTIVE: 'ACTIVE',
  DISABLED: 'DISABLED'
} as const

export const MACHINE_PRINCIPAL_STATUS_VALUES = Object.values(MACHINE_PRINCIPAL_STATUSES)

export const API_KEY_STATUSES = {
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED'
} as const

export const API_KEY_STATUS_VALUES = Object.values(API_KEY_STATUSES)
