// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const ASSET_INTERNAL_PERMISSION_CODES = {
  AVATAR_RESOLVE_PUBLIC_URL: 'asset.internal.avatar.resolve_public_url'
} as const
