// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const ASSET_SITE_MEDIA_PERMISSION_CODES = {
  UPLOAD: 'asset.site_media.upload',
  READ: 'asset.site_media.read',
  DELIVERY_MANAGE: 'asset.site_media.delivery.manage',
  ARCHIVE: 'asset.site_media.archive',
  TAKEDOWN: 'asset.site_media.takedown',
  DELETE: 'asset.site_media.delete',
  RESOLVE: 'asset.internal.site_media.resolve',
  PUBLICATION_PROTECT: 'asset.internal.site_media.publication.protect',
  PUBLICATION_RELEASE: 'asset.internal.site_media.publication.release'
} as const
