// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const CRM_INTERNAL_PERMISSION_CODES = {
  VALIDATE_OBJECT_REFERENCE: 'crm.internal.object_reference.validate'
} as const
