// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const CRM_MANAGEMENT_PERMISSION_CODES = {
  READ_CRM_ACCOUNT: 'crm.account.read',
  CREATE_CRM_ACCOUNT: 'crm.account.create',
  UPDATE_CRM_ACCOUNT: 'crm.account.update',
  CONVERT_CRM_ACCOUNT: 'crm.account.convert',
  CLAIM_CRM_ACCOUNT: 'crm.account.claim',
  MANAGE_CRM_ACCOUNT: 'crm.account.manage',
  VIEW_RESTRICTED_DUPLICATE: 'crm.duplicate.viewRestricted',
  MANAGE_CRM_CONTACT: 'crm.contact.manage',
  MANAGE_CRM_SOURCE: 'crm.source.manage',
  CREATE_CRM_ACTIVITY: 'crm.activity.create',
  MANAGE_CRM_OPPORTUNITY: 'crm.opportunity.manage'
} as const
