// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const SITE_MANAGEMENT_INTERNAL_PERMISSION_CODES = {
  RUNTIME_CAPABILITY_REGISTER: 'site.internal.runtime.capability.register',
  RUNTIME_PUBLICATION_READ: 'site.internal.runtime.publication.read',
  RUNTIME_SYNC_REPORT: 'site.internal.runtime.sync.report',
  RUNTIME_PREVIEW_READ: 'site.internal.runtime.preview.read'
} as const
