// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const SITE_MANAGEMENT_PERMISSION_CODES = {
  READ: 'site.management.read',
  MANAGE: 'site.management.manage',
  LOCALE_MANAGE: 'site.management.locale.manage',
  PRODUCT_MANAGE: 'site.management.product.manage',
  CONTENT_MANAGE: 'site.management.content.manage',
  SYNC: 'site.management.sync',
  CREDENTIAL_MANAGE: 'site.management.credential.manage',
  AUDIT_READ: 'site.management.audit.read',
  PREVIEW: 'site.management.preview'
} as const
