// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const WMS_MANAGEMENT_PERMISSION_CODES = {
  READ_WAREHOUSE: 'wms.warehouse.read',
  READ_LOCATION: 'wms.location.read',
  READ_RECEIPT: 'wms.receipt.read',
  MANAGE_RECEIPT: 'wms.receipt.manage',
  READ_INVENTORY: 'wms.inventory.read'
} as const
