export const DEFAULT_COUNTRY_CODE = 'CN:+86';

export const PHONE_COUNTRY_OPTIONS = [
  { label: 'Afghanistan (+93)', value: 'AF:+93' },
  { label: 'Albania (+355)', value: 'AL:+355' },
  { label: 'Algeria (+213)', value: 'DZ:+213' },
  { label: 'American Samoa (+1)', value: 'AS:+1' },
  { label: 'Andorra (+376)', value: 'AD:+376' },
  { label: 'Angola (+244)', value: 'AO:+244' },
  { label: 'Anguilla (+1)', value: 'AI:+1' },
  { label: 'Antigua and Barbuda (+1)', value: 'AG:+1' },
  { label: 'Argentina (+54)', value: 'AR:+54' },
  { label: 'Armenia (+374)', value: 'AM:+374' },
  { label: 'Aruba (+297)', value: 'AW:+297' },
  { label: 'Australia (+61)', value: 'AU:+61' },
  { label: 'Austria (+43)', value: 'AT:+43' },
  { label: 'Azerbaijan (+994)', value: 'AZ:+994' },
  { label: 'Bahamas (+1)', value: 'BS:+1' },
  { label: 'Bahrain (+973)', value: 'BH:+973' },
  { label: 'Bangladesh (+880)', value: 'BD:+880' },
  { label: 'Barbados (+1)', value: 'BB:+1' },
  { label: 'Belarus (+375)', value: 'BY:+375' },
  { label: 'Belgium (+32)', value: 'BE:+32' },
  { label: 'Belize (+501)', value: 'BZ:+501' },
  { label: 'Benin (+229)', value: 'BJ:+229' },
  { label: 'Bermuda (+1)', value: 'BM:+1' },
  { label: 'Bhutan (+975)', value: 'BT:+975' },
  { label: 'Bolivia (+591)', value: 'BO:+591' },
  { label: 'Bosnia and Herzegovina (+387)', value: 'BA:+387' },
  { label: 'Botswana (+267)', value: 'BW:+267' },
  { label: 'Brazil (+55)', value: 'BR:+55' },
  { label: 'British Virgin Islands (+1)', value: 'VG:+1' },
  { label: 'Brunei (+673)', value: 'BN:+673' },
  { label: 'Bulgaria (+359)', value: 'BG:+359' },
  { label: 'Burkina Faso (+226)', value: 'BF:+226' },
  { label: 'Burundi (+257)', value: 'BI:+257' },
  { label: 'Cambodia (+855)', value: 'KH:+855' },
  { label: 'Cameroon (+237)', value: 'CM:+237' },
  { label: 'Canada (+1)', value: 'CA:+1' },
  { label: 'Cape Verde (+238)', value: 'CV:+238' },
  { label: 'Cayman Islands (+1)', value: 'KY:+1' },
  { label: 'Central African Republic (+236)', value: 'CF:+236' },
  { label: 'Chad (+235)', value: 'TD:+235' },
  { label: 'Chile (+56)', value: 'CL:+56' },
  { label: 'China (+86)', value: 'CN:+86' },
  { label: 'Colombia (+57)', value: 'CO:+57' },
  { label: 'Comoros (+269)', value: 'KM:+269' },
  { label: 'Congo - Brazzaville (+242)', value: 'CG:+242' },
  { label: 'Congo - Kinshasa (+243)', value: 'CD:+243' },
  { label: 'Cook Islands (+682)', value: 'CK:+682' },
  { label: 'Costa Rica (+506)', value: 'CR:+506' },
  { label: "Cote d'Ivoire (+225)", value: 'CI:+225' },
  { label: 'Croatia (+385)', value: 'HR:+385' },
  { label: 'Cuba (+53)', value: 'CU:+53' },
  { label: 'Curacao (+599)', value: 'CW:+599' },
  { label: 'Cyprus (+357)', value: 'CY:+357' },
  { label: 'Czechia (+420)', value: 'CZ:+420' },
  { label: 'Denmark (+45)', value: 'DK:+45' },
  { label: 'Djibouti (+253)', value: 'DJ:+253' },
  { label: 'Dominica (+1)', value: 'DM:+1' },
  { label: 'Dominican Republic (+1)', value: 'DO:+1' },
  { label: 'Ecuador (+593)', value: 'EC:+593' },
  { label: 'Egypt (+20)', value: 'EG:+20' },
  { label: 'El Salvador (+503)', value: 'SV:+503' },
  { label: 'Equatorial Guinea (+240)', value: 'GQ:+240' },
  { label: 'Eritrea (+291)', value: 'ER:+291' },
  { label: 'Estonia (+372)', value: 'EE:+372' },
  { label: 'Eswatini (+268)', value: 'SZ:+268' },
  { label: 'Ethiopia (+251)', value: 'ET:+251' },
  { label: 'Faroe Islands (+298)', value: 'FO:+298' },
  { label: 'Fiji (+679)', value: 'FJ:+679' },
  { label: 'Finland (+358)', value: 'FI:+358' },
  { label: 'France (+33)', value: 'FR:+33' },
  { label: 'French Guiana (+594)', value: 'GF:+594' },
  { label: 'French Polynesia (+689)', value: 'PF:+689' },
  { label: 'Gabon (+241)', value: 'GA:+241' },
  { label: 'Gambia (+220)', value: 'GM:+220' },
  { label: 'Georgia (+995)', value: 'GE:+995' },
  { label: 'Germany (+49)', value: 'DE:+49' },
  { label: 'Ghana (+233)', value: 'GH:+233' },
  { label: 'Gibraltar (+350)', value: 'GI:+350' },
  { label: 'Greece (+30)', value: 'GR:+30' },
  { label: 'Greenland (+299)', value: 'GL:+299' },
  { label: 'Grenada (+1)', value: 'GD:+1' },
  { label: 'Guadeloupe (+590)', value: 'GP:+590' },
  { label: 'Guam (+1)', value: 'GU:+1' },
  { label: 'Guatemala (+502)', value: 'GT:+502' },
  { label: 'Guinea (+224)', value: 'GN:+224' },
  { label: 'Guinea-Bissau (+245)', value: 'GW:+245' },
  { label: 'Guyana (+592)', value: 'GY:+592' },
  { label: 'Haiti (+509)', value: 'HT:+509' },
  { label: 'Honduras (+504)', value: 'HN:+504' },
  { label: 'Hong Kong SAR China (+852)', value: 'HK:+852' },
  { label: 'Hungary (+36)', value: 'HU:+36' },
  { label: 'Iceland (+354)', value: 'IS:+354' },
  { label: 'India (+91)', value: 'IN:+91' },
  { label: 'Indonesia (+62)', value: 'ID:+62' },
  { label: 'Iran (+98)', value: 'IR:+98' },
  { label: 'Iraq (+964)', value: 'IQ:+964' },
  { label: 'Ireland (+353)', value: 'IE:+353' },
  { label: 'Isle of Man (+44)', value: 'IM:+44' },
  { label: 'Israel (+972)', value: 'IL:+972' },
  { label: 'Italy (+39)', value: 'IT:+39' },
  { label: 'Jamaica (+1)', value: 'JM:+1' },
  { label: 'Japan (+81)', value: 'JP:+81' },
  { label: 'Jersey (+44)', value: 'JE:+44' },
  { label: 'Jordan (+962)', value: 'JO:+962' },
  { label: 'Kazakhstan (+7)', value: 'KZ:+7' },
  { label: 'Kenya (+254)', value: 'KE:+254' },
  { label: 'Kiribati (+686)', value: 'KI:+686' },
  { label: 'Kuwait (+965)', value: 'KW:+965' },
  { label: 'Kyrgyzstan (+996)', value: 'KG:+996' },
  { label: 'Laos (+856)', value: 'LA:+856' },
  { label: 'Latvia (+371)', value: 'LV:+371' },
  { label: 'Lebanon (+961)', value: 'LB:+961' },
  { label: 'Lesotho (+266)', value: 'LS:+266' },
  { label: 'Liberia (+231)', value: 'LR:+231' },
  { label: 'Libya (+218)', value: 'LY:+218' },
  { label: 'Liechtenstein (+423)', value: 'LI:+423' },
  { label: 'Lithuania (+370)', value: 'LT:+370' },
  { label: 'Luxembourg (+352)', value: 'LU:+352' },
  { label: 'Macao SAR China (+853)', value: 'MO:+853' },
  { label: 'Madagascar (+261)', value: 'MG:+261' },
  { label: 'Malawi (+265)', value: 'MW:+265' },
  { label: 'Malaysia (+60)', value: 'MY:+60' },
  { label: 'Maldives (+960)', value: 'MV:+960' },
  { label: 'Mali (+223)', value: 'ML:+223' },
  { label: 'Malta (+356)', value: 'MT:+356' },
  { label: 'Marshall Islands (+692)', value: 'MH:+692' },
  { label: 'Martinique (+596)', value: 'MQ:+596' },
  { label: 'Mauritania (+222)', value: 'MR:+222' },
  { label: 'Mauritius (+230)', value: 'MU:+230' },
  { label: 'Mayotte (+262)', value: 'YT:+262' },
  { label: 'Mexico (+52)', value: 'MX:+52' },
  { label: 'Micronesia (+691)', value: 'FM:+691' },
  { label: 'Moldova (+373)', value: 'MD:+373' },
  { label: 'Monaco (+377)', value: 'MC:+377' },
  { label: 'Mongolia (+976)', value: 'MN:+976' },
  { label: 'Montenegro (+382)', value: 'ME:+382' },
  { label: 'Montserrat (+1)', value: 'MS:+1' },
  { label: 'Morocco (+212)', value: 'MA:+212' },
  { label: 'Mozambique (+258)', value: 'MZ:+258' },
  { label: 'Myanmar (+95)', value: 'MM:+95' },
  { label: 'Namibia (+264)', value: 'NA:+264' },
  { label: 'Nauru (+674)', value: 'NR:+674' },
  { label: 'Nepal (+977)', value: 'NP:+977' },
  { label: 'Netherlands (+31)', value: 'NL:+31' },
  { label: 'New Caledonia (+687)', value: 'NC:+687' },
  { label: 'New Zealand (+64)', value: 'NZ:+64' },
  { label: 'Nicaragua (+505)', value: 'NI:+505' },
  { label: 'Niger (+227)', value: 'NE:+227' },
  { label: 'Nigeria (+234)', value: 'NG:+234' },
  { label: 'North Korea (+850)', value: 'KP:+850' },
  { label: 'North Macedonia (+389)', value: 'MK:+389' },
  { label: 'Northern Mariana Islands (+1)', value: 'MP:+1' },
  { label: 'Norway (+47)', value: 'NO:+47' },
  { label: 'Oman (+968)', value: 'OM:+968' },
  { label: 'Pakistan (+92)', value: 'PK:+92' },
  { label: 'Palau (+680)', value: 'PW:+680' },
  { label: 'Palestine (+970)', value: 'PS:+970' },
  { label: 'Panama (+507)', value: 'PA:+507' },
  { label: 'Papua New Guinea (+675)', value: 'PG:+675' },
  { label: 'Paraguay (+595)', value: 'PY:+595' },
  { label: 'Peru (+51)', value: 'PE:+51' },
  { label: 'Philippines (+63)', value: 'PH:+63' },
  { label: 'Poland (+48)', value: 'PL:+48' },
  { label: 'Portugal (+351)', value: 'PT:+351' },
  { label: 'Puerto Rico (+1)', value: 'PR:+1' },
  { label: 'Qatar (+974)', value: 'QA:+974' },
  { label: 'Reunion (+262)', value: 'RE:+262' },
  { label: 'Romania (+40)', value: 'RO:+40' },
  { label: 'Russia (+7)', value: 'RU:+7' },
  { label: 'Rwanda (+250)', value: 'RW:+250' },
  { label: 'Saint Kitts and Nevis (+1)', value: 'KN:+1' },
  { label: 'Saint Lucia (+1)', value: 'LC:+1' },
  { label: 'Saint Martin (+590)', value: 'MF:+590' },
  { label: 'Saint Pierre and Miquelon (+508)', value: 'PM:+508' },
  { label: 'Saint Vincent and the Grenadines (+1)', value: 'VC:+1' },
  { label: 'Samoa (+685)', value: 'WS:+685' },
  { label: 'San Marino (+378)', value: 'SM:+378' },
  { label: 'Sao Tome and Principe (+239)', value: 'ST:+239' },
  { label: 'Saudi Arabia (+966)', value: 'SA:+966' },
  { label: 'Senegal (+221)', value: 'SN:+221' },
  { label: 'Serbia (+381)', value: 'RS:+381' },
  { label: 'Seychelles (+248)', value: 'SC:+248' },
  { label: 'Sierra Leone (+232)', value: 'SL:+232' },
  { label: 'Singapore (+65)', value: 'SG:+65' },
  { label: 'Sint Maarten (+1)', value: 'SX:+1' },
  { label: 'Slovakia (+421)', value: 'SK:+421' },
  { label: 'Slovenia (+386)', value: 'SI:+386' },
  { label: 'Solomon Islands (+677)', value: 'SB:+677' },
  { label: 'Somalia (+252)', value: 'SO:+252' },
  { label: 'South Africa (+27)', value: 'ZA:+27' },
  { label: 'South Korea (+82)', value: 'KR:+82' },
  { label: 'South Sudan (+211)', value: 'SS:+211' },
  { label: 'Spain (+34)', value: 'ES:+34' },
  { label: 'Sri Lanka (+94)', value: 'LK:+94' },
  { label: 'Sudan (+249)', value: 'SD:+249' },
  { label: 'Suriname (+597)', value: 'SR:+597' },
  { label: 'Sweden (+46)', value: 'SE:+46' },
  { label: 'Switzerland (+41)', value: 'CH:+41' },
  { label: 'Syria (+963)', value: 'SY:+963' },
  { label: 'Taiwan (+886)', value: 'TW:+886' },
  { label: 'Tajikistan (+992)', value: 'TJ:+992' },
  { label: 'Tanzania (+255)', value: 'TZ:+255' },
  { label: 'Thailand (+66)', value: 'TH:+66' },
  { label: 'Timor-Leste (+670)', value: 'TL:+670' },
  { label: 'Togo (+228)', value: 'TG:+228' },
  { label: 'Tonga (+676)', value: 'TO:+676' },
  { label: 'Trinidad and Tobago (+1)', value: 'TT:+1' },
  { label: 'Tunisia (+216)', value: 'TN:+216' },
  { label: 'Turkey (+90)', value: 'TR:+90' },
  { label: 'Turkmenistan (+993)', value: 'TM:+993' },
  { label: 'Turks and Caicos Islands (+1)', value: 'TC:+1' },
  { label: 'Tuvalu (+688)', value: 'TV:+688' },
  { label: 'U.S. Virgin Islands (+1)', value: 'VI:+1' },
  { label: 'Uganda (+256)', value: 'UG:+256' },
  { label: 'Ukraine (+380)', value: 'UA:+380' },
  { label: 'United Arab Emirates (+971)', value: 'AE:+971' },
  { label: 'United Kingdom (+44)', value: 'GB:+44' },
  { label: 'United States (+1)', value: 'US:+1' },
  { label: 'Uruguay (+598)', value: 'UY:+598' },
  { label: 'Uzbekistan (+998)', value: 'UZ:+998' },
  { label: 'Vanuatu (+678)', value: 'VU:+678' },
  { label: 'Vatican City (+39)', value: 'VA:+39' },
  { label: 'Venezuela (+58)', value: 'VE:+58' },
  { label: 'Vietnam (+84)', value: 'VN:+84' },
  { label: 'Wallis and Futuna (+681)', value: 'WF:+681' },
  { label: 'Yemen (+967)', value: 'YE:+967' },
  { label: 'Zambia (+260)', value: 'ZM:+260' },
  { label: 'Zimbabwe (+263)', value: 'ZW:+263' },
];

// Returns the matching phone country option for a stored select value.
export function getPhoneCountryOption(countryCode: string) {
  return (
    PHONE_COUNTRY_OPTIONS.find((option) => option.value === countryCode) ??
    PHONE_COUNTRY_OPTIONS.find((option) => option.value === DEFAULT_COUNTRY_CODE)
  );
}

// Extracts the dialing prefix from the selected country option value.
export function resolveDialCode(countryCode: string) {
  const [, dialCode] = `${countryCode ?? DEFAULT_COUNTRY_CODE}`.split(':');
  return dialCode || '+86';
}

// Normalizes a locally entered phone number before it is combined with the selected country code.
export function normalizeLocalPhoneNumber(phoneNumber: string) {
  return `${phoneNumber ?? ''}`.replace(/\D/g, '');
}

// Builds the final E.164-like phone number the auth APIs expect from country and local number inputs.
export function buildPhoneNumber(countryCode: string, phoneNumber: string) {
  const normalizedCountryCode = resolveDialCode(countryCode).trim() || '+86';
  const normalizedPhoneNumber = normalizeLocalPhoneNumber(phoneNumber);
  return `${normalizedCountryCode}${normalizedPhoneNumber}`;
}
