import { describe, it, test } from 'node:test'
import { expect } from '../../../../../common/src/testing/static-check-assertions.mjs'
import { fileURLToPath } from 'node:url'
const __dirname = fileURLToPath(new URL('.', import.meta.url))
import { readFileSync, readdirSync } from 'node:fs';
import { resolve } from 'node:path';
/** Verifies the retired inverse generator cannot become a second Permission semantic source. */
describe('Common-owned permission catalog', () => {
    it('contains no generated banner or inverse package script', () => {
        const root = resolve(__dirname, '../../../../../common/src/authorization/permission-codes');
        expect(readFileSync(resolve(root, 'index.ts'), 'utf8')).not.toContain('Generated by permission-service');
        const packageJson = readFileSync(resolve(__dirname, '../../package.json'), 'utf8');
        expect(packageJson).not.toContain('permission-codes:generate-common');
    });
    it('does not retire a Permission Code while production services still consume it', () => {
        const servicesRoot = resolve(__dirname, '../../../..');
        const ignoredPathParts = [
            '/test/',
            '.spec.ts',
            '.test.ts',
            '/dist/',
            '/generated/',
            '/permission-service/src/scripts/sync-permission-codes.ts'
        ];
        const ignoredDirectoryNames = new Set(['test', 'dist', 'generated', 'node_modules']);
        const sourceFiles: string[] = [];
        /** Collects production TypeScript files without traversing generated or test trees. */
        const collectSourceFiles = (directory: string): void => {
            for (const entry of readdirSync(directory, { withFileTypes: true })) {
                const path = resolve(directory, entry.name);
                if (entry.isDirectory() && !ignoredDirectoryNames.has(entry.name))
                    collectSourceFiles(path);
                else if (entry.isFile() && path.endsWith('.ts'))
                    sourceFiles.push(path);
            }
        };
        collectSourceFiles(servicesRoot);
        const productionSource = sourceFiles
            .filter((path) => !ignoredPathParts.some((part) => path.includes(part)))
            .map((path) => readFileSync(path, 'utf8'))
            .join('\n');
        const deprecatedSource = readFileSync(
            resolve(__dirname, '../../../../../common/src/authorization/permission-codes/deprecated.permission-codes.ts'),
            'utf8'
        );
        const deprecatedCodes = [...deprecatedSource.matchAll(/^\s*['"]([^'"]+)['"],?$/gm)].map((match) => match[1]);
        const consumedDeprecatedCodes = deprecatedCodes.filter(
            (code) => productionSource.includes(`'${code}'`) || productionSource.includes(`"${code}"`)
        );
        expect(consumedDeprecatedCodes).toEqual([]);
    });
});
