// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PUBLIC_ENTRY_BUSINESS_CARD_PERMISSION_CODES = {
  READ: 'public-entry.business-card.read',
  MANAGE: 'public-entry.business-card.manage',
  ENABLE: 'public-entry.business-card.enable',
  DISABLE: 'public-entry.business-card.disable',
  PUBLIC_ENTRY_MANAGE: 'public-entry.business-card.public-entry.manage',
  STATS_READ: 'public-entry.business-card.stats.read'
} as const
