// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const PUBLIC_ENTRY_SHORT_LINK_PERMISSION_CODES = {
  READ: 'public-entry.short-link.read',
  CREATE: 'public-entry.short-link.create',
  UPDATE: 'public-entry.short-link.update',
  DISABLE: 'public-entry.short-link.disable',
  ARCHIVE: 'public-entry.short-link.archive',
  STATS_READ: 'public-entry.short-link.stats.read'
} as const
