// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const COLLABORATION_ANNOTATION_PERMISSION_CODES = {
  CREATE: 'collaboration.annotation.create',
  MANAGE: 'collaboration.annotation.manage'
} as const
