// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const COLLABORATION_TASK_PERMISSION_CODES = {
  CREATE: 'collaboration.task.create',
  ASSIGN: 'collaboration.task.assign'
} as const
