// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const TERMINAL_DEVICE_INTERNAL_PERMISSION_CODES = {
  ACTIVATE_ENROLLMENT: 'terminal-device.internal.gateway.enrollment.activate',
  RESOLVE_ACCESS: 'terminal-device.internal.gateway.access.resolve',
  RECORD_HEARTBEAT: 'terminal-device.internal.gateway.heartbeat.record',
  RECORD_DIAGNOSTIC_LOG: 'terminal-device.internal.gateway.diagnostic_log.record'
} as const
