// Generated by permission-service permission-codes:generate-common. Do not edit manually.
export const TERMINAL_DEVICE_MANAGEMENT_PERMISSION_CODES = {
  CREATE_ENROLLMENT: 'terminal-device.enrollment.create',
  REVOKE_ENROLLMENT: 'terminal-device.enrollment.revoke',
  READ_DEVICE: 'terminal-device.read',
  READ_SENSITIVE_DEVICE: 'terminal-device.sensitive.read',
  DISABLE_DEVICE: 'terminal-device.status.disable',
  MARK_LOST_DEVICE: 'terminal-device.status.mark-lost',
  MARK_MAINTENANCE_DEVICE: 'terminal-device.status.mark-maintenance',
  RESTORE_ACTIVE_DEVICE: 'terminal-device.status.restore-active',
  MANAGE_VERSION_POLICY: 'terminal-device.version-policy.manage',
  READ_AUDIT: 'terminal-device.audit.read'
} as const
