import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'

const base = new URL('..', import.meta.url)
const repo = new URL('../../..', import.meta.url)
const workflow = readFileSync(new URL('.github/workflows/ci.yml', repo), 'utf8')
const packageJson = JSON.parse(readFileSync(new URL('package.json', repo), 'utf8'))
assert.match(workflow, /merge_group:/)
assert.match(workflow, /name: Baseline Checks/)
assert.match(workflow, /^  static-risk:\n/m)
assert.match(workflow, /^  l2-runtime:\n/m)
assert.match(workflow, /^  baseline:\n/m)
assert.match(workflow, /^    if: \$\{\{ always\(\) \}\}$/m)
assert.match(workflow, /^    needs: \[static-risk, l2-runtime\]$/m)
assert.match(
  workflow,
  /OES_CI_TASK_KEY: ci_\$\{\{ github\.run_id \}\}_\$\{\{ github\.run_attempt \}\}_static/
)
assert.match(
  workflow,
  /OES_CI_TASK_KEY: ci_\$\{\{ github\.run_id \}\}_\$\{\{ github\.run_attempt \}\}_l2/
)
assert.match(workflow, /^\s*run: pnpm env:ensure -- --task-key="\$\{OES_CI_TASK_KEY\}"$/m)
assert.match(workflow, /^\s*run: pnpm generated:all$/m)
assert.match(workflow, /^\s*run: pnpm build:prepared$/m)
assert.match(workflow, /^\s*run: pnpm test:risk$/m)
assert.match(workflow, /^\s*run: pnpm test:l2$/m)
assert.match(workflow, /test "\$\{STATIC_RISK_RESULT\}" = "success"/)
assert.match(workflow, /test "\$\{L2_RUNTIME_RESULT\}" = "success"/)
assert.equal((workflow.match(/^\s*run: pnpm generated:all$/gm) ?? []).length, 1)
assert.equal((workflow.match(/^\s*run: pnpm test:risk$/gm) ?? []).length, 1)
assert.equal((workflow.match(/^\s*run: pnpm test:l2$/gm) ?? []).length, 1)
assert.match(packageJson.scripts['build:prepared'], /tsc -b tsconfig\.json/)
assert.doesNotMatch(packageJson.scripts['build:prepared'], /generated:all/)
assert.match(packageJson.scripts['test:risk'], /pnpm collaboration-runtime:check/)
assert.match(
  packageJson.scripts['test:risk'],
  /node --test scripts\/local\/foundation-trusted-grpc-atomic-group\.spec\.mjs/
)
const entry = readFileSync(new URL('bin/oes-remote-driver', base), 'utf8')
assert.match(entry, /^#!\/bin\/sh\nset -eu\n/)
assert.match(entry, /exec node --experimental-strip-types/)
assert.doesNotMatch(entry, /git |gh |curl /)
const profile = readFileSync(new URL('profile/oes-project-owner.config.toml', base), 'utf8')
assert.match(profile, /approval_policy = "on-request"/)
assert.match(profile, /approvals_reviewer = "auto_review"/)
assert.match(profile, /allow_local_binding = true/)
assert.match(profile, /"\*\*\/\.env" = "deny"/)
assert.match(profile, /trusted_authorization_root = "{{TRUSTED_AUTHORIZATION_ROOT}}"/)
assert.match(profile, /"{{TRUSTED_AUTHORIZATION_ROOT}}" = "read"/)
assert.doesNotMatch(profile, /OES_REMOTE_AUTHORIZATION_ROOT|OES_REMOTE_ADMISSION_ROOT/)
assert.match(profile, /"{{OWNER_GIT_DIRECTORY}}" = "write"/)
assert.doesNotMatch(profile, /GIT_COMMON_DIRECTORY.*write/)
const cli = readFileSync(new URL('src/cli.ts', base), 'utf8')
assert.match(cli, /profile-preflight/)
assert.match(cli, /schema-validate/)
assert.match(cli, /ud-queue-view/)
assert.match(cli, /ci-recovery-decision/)
assert.match(cli, /local-main/)
assert.match(cli, /--profile-report/)
assert.match(cli, /--child-authorization/)
assert.match(readFileSync(new URL('src/binding.ts', base), 'utf8'), /current-stage-cleanup\.json/)
assert.doesNotMatch(cli, /flag\(args, '--owner'\)/)
assert.doesNotMatch(cli, /OES_REMOTE_AUTHORIZATION_ROOT|OES_REMOTE_ADMISSION_ROOT/)
assert.doesNotMatch(cli, /binding-fingerprint|cleanup-fingerprint/)
const proposalQueue = readFileSync(new URL('src/proposal-queue.ts', base), 'utf8')
assert.match(proposalQueue, /PROPOSAL_FIFO_ADMISSION_VIOLATION/)
assert.match(proposalQueue, /PROPOSAL_TERMINAL_EXACT_RETURN_UNPROVEN/)
assert.doesNotMatch(proposalQueue, /writeFile|setInterval|setTimeout/)
const retryPolicy = readFileSync(new URL('src/retry-policy.ts', base), 'utf8')
assert.match(retryPolicy, /maxRetries: 3/)
assert.match(retryPolicy, /EXTERNAL_PERMISSION_BLOCKER/)
const localMain = readFileSync(new URL('src/local-main.ts', base), 'utf8')
assert.match(localMain, /\['merge', '--ff-only'/)
assert.match(localMain, /\['fetch', '--no-tags', binding\.remote, binding\.branch\]/)
assert.doesNotMatch(localMain, /\['(?:reset|stash|rebase|checkout)'|setInterval|setTimeout/)
const schemaValidator = readFileSync(new URL('src/schema-validation.ts', base), 'utf8')
assert.match(schemaValidator, /JSON_SCHEMA_VALIDATION_FAILED/)
assert.match(schemaValidator, /JSON_SCHEMA_KEYWORD_UNSUPPORTED/)
assert.match(schemaValidator, /schema\.not/)
for (const file of readdirSync(new URL('schemas', base)))
  JSON.parse(readFileSync(new URL(`schemas/${file}`, base), 'utf8'))
console.log('collaboration-runtime static checks: PASS')
