import assert from 'node:assert/strict'
import { readFileSync, readdirSync } from 'node:fs'

const base = new URL('..', import.meta.url)
const repo = new URL('../../..', import.meta.url)
const workflow = readFileSync(new URL('.github/workflows/ci.yml', repo), 'utf8')
assert.match(workflow, /merge_group:/)
assert.match(workflow, /name: Baseline Checks/)
assert.match(workflow, /pnpm collaboration-runtime:check/)
const entry = readFileSync(new URL('bin/oes-remote-driver', base), 'utf8')
assert.match(entry, /^#!\/bin\/sh\nset -eu\n/)
assert.match(entry, /exec node --experimental-strip-types/)
assert.doesNotMatch(entry, /git |gh |curl /)
const profile = readFileSync(new URL('profile/oes-project-owner.config.toml', base), 'utf8')
assert.match(profile, /approval_policy = "on-request"/)
assert.match(profile, /approvals_reviewer = "auto_review"/)
assert.match(profile, /allow_local_binding = true/)
assert.match(profile, /"\*\*\/\.env" = "deny"/)
assert.match(profile, /trusted_authorization_root = "{{TRUSTED_AUTHORIZATION_ROOT}}"/)
assert.match(profile, /"{{TRUSTED_AUTHORIZATION_ROOT}}" = "read"/)
assert.doesNotMatch(profile, /OES_REMOTE_AUTHORIZATION_ROOT|OES_REMOTE_ADMISSION_ROOT/)
assert.match(profile, /"{{OWNER_GIT_DIRECTORY}}" = "write"/)
assert.doesNotMatch(profile, /GIT_COMMON_DIRECTORY.*write/)
const cli = readFileSync(new URL('src/cli.ts', base), 'utf8')
assert.match(cli, /profile-preflight/)
assert.match(cli, /schema-validate/)
assert.match(cli, /--profile-report/)
assert.match(cli, /--child-authorization/)
assert.doesNotMatch(cli, /flag\(args, '--owner'\)/)
assert.doesNotMatch(cli, /OES_REMOTE_AUTHORIZATION_ROOT|OES_REMOTE_ADMISSION_ROOT/)
assert.doesNotMatch(cli, /binding-fingerprint|cleanup-fingerprint/)
const schemaValidator = readFileSync(new URL('src/schema-validation.ts', base), 'utf8')
assert.match(schemaValidator, /JSON_SCHEMA_VALIDATION_FAILED/)
assert.match(schemaValidator, /JSON_SCHEMA_KEYWORD_UNSUPPORTED/)
assert.match(schemaValidator, /schema\.not/)
for (const file of readdirSync(new URL('schemas', base)))
  JSON.parse(readFileSync(new URL(`schemas/${file}`, base), 'utf8'))
console.log('collaboration-runtime static checks: PASS')
