export const INTERNAL_SERVICE_AUTHENTICATOR = Symbol('INTERNAL_SERVICE_AUTHENTICATOR')
export const OPERATOR_CONTEXT_SIGNER = Symbol('OPERATOR_CONTEXT_SIGNER')
export const OPERATOR_CONTEXT_VERIFIER = Symbol('OPERATOR_CONTEXT_VERIFIER')
export const OPERATOR_PERMISSION_RESOLVER = Symbol('OPERATOR_PERMISSION_RESOLVER')
