import { Test } from '@nestjs/testing'
import { of } from 'rxjs'
import { IdentityTrustedExecutionModule } from '../../src/modules/identity-trusted-execution.module'
import { IdentityPartyTrustedGrpcClient } from '../../src/infrastructure/adaptors/party-trusted-grpc.client'
import { IdentityPartyMachineSourceCredentialClient } from '../../src/infrastructure/adaptors/identity-party-machine-source-credential.client'
import { IdentityPartyMachineSourceCredentialProvider } from '../../src/infrastructure/adaptors/identity-party-machine-source-credential.provider'
import { IdentityPartyExecutionTokenExchangeClient } from '../../src/infrastructure/adaptors/identity-party-execution-token-exchange.client'
import { IdentityPartyTrustedGrpcExecutionProducer } from '../../src/infrastructure/adaptors/identity-party-trusted-grpc-execution.producer'
const code='party.internal.register_tenant_party'; const audience='urn:oes:service:party-service'; const trace='00-0123456789abcdef0123456789abcdef-0123456789abcdef-01'
describe('Identity Party trusted execution',()=>{const env=process.env
  beforeEach(()=>{process.env={...env,AUTH_EXECUTION_ISSUER:'https://issuer.example',OES_WORKLOAD_SPIFFE_ID:'spiffe://oes/identity-service',IDENTITY_PARTY_MACHINE_PRINCIPAL_ID:'machine-identity',IDENTITY_PARTY_MACHINE_WORKLOAD_BINDING_ID:'binding-identity',IDENTITY_PARTY_MACHINE_WORKLOAD_BINDING_VERSION:'1'}});afterAll(()=>{process.env=env})
  it('resolves its dedicated DI graph',async()=>{const m=await Test.createTestingModule({imports:[IdentityTrustedExecutionModule]}).compile();for(const t of [IdentityPartyTrustedGrpcClient,IdentityPartyMachineSourceCredentialClient,IdentityPartyMachineSourceCredentialProvider,IdentityPartyExecutionTokenExchangeClient,IdentityPartyTrustedGrpcExecutionProducer])expect(m.get(t)).toBeDefined();await m.close()})
  it('uses Identity selector and rejects empty source credential',async()=>{const c=new IdentityPartyMachineSourceCredentialClient();const rpc=jest.fn(()=>of({tokenType:'Bearer',sourceCredential:'source'}));(c as any).get=()=>({issueMachineWorkloadSourceCredential:rpc});await expect(c.issue()).resolves.toBe('source');expect(rpc).toHaveBeenCalledWith({machinePrincipalId:'machine-identity',machineWorkloadBindingId:'binding-identity',machineWorkloadBindingVersion:'1'},expect.anything());(c as any).get=()=>({issueMachineWorkloadSourceCredential:()=>of({tokenType:'Bearer',sourceCredential:''})});await expect(c.issue()).rejects.toThrow('PARTY_CALLER_SOURCE_CREDENTIAL_INVALID')})
  it('fails closed before callback for missing config and source rejection',async()=>{const c=new IdentityPartyMachineSourceCredentialClient();delete process.env.IDENTITY_PARTY_MACHINE_WORKLOAD_BINDING_VERSION;await expect(c.issue()).rejects.toThrow('PARTY_CALLER_FOUNDATION_UNAVAILABLE');process.env.IDENTITY_PARTY_MACHINE_WORKLOAD_BINDING_VERSION='1';(c as any).get=()=>({issueMachineWorkloadSourceCredential:()=>{throw new Error('source credential rejected')}});const p=new IdentityPartyMachineSourceCredentialProvider(c);const cb=jest.fn(async()=>undefined);await expect(p.run(cb)).rejects.toThrow('source credential rejected');expect(cb).not.toHaveBeenCalled()})
  it('executes Identity exchange and maps wrong audience through producer',async()=>{const e=new IdentityPartyExecutionTokenExchangeClient();(e as any).get=()=>({exchangeExecutionToken:()=>of({accessToken:'',tokenType:'Bearer',grantedAudience:audience,grantedPermissionCodes:[code]})});await expect(e.exchange({targetAudience:audience,requestedPermissionCodes:[code]},{} as never)).resolves.toMatchObject({grantedAudience:audience});const producer=new IdentityPartyTrustedGrpcExecutionProducer({accessor:{},run:async()=>{throw new Error('ExecutionToken exchange granted an unexpected audience')}} as never,e);await expect(producer.createMetadata(code,'request-1',trace)).rejects.toThrow('PARTY_CALLER_SOURCE_CREDENTIAL_INVALID')})
})
